### ISSUE TITLE
分页功能 不能选择每页显示条数

### ISSUE THREAD

**Issue by cncert** [newpanjing/simpleui#10]
分页功能 不能选择每页显示条数，如果可以在配置文件里配置每页显示的条数就完美了

**Comment by newpanjing** [comment]
这个是需要在admin中设置的，而不是页面自定义设置。

例如：
```python
@admin.register(Article)
class ArticleAdmin(admin.ModelAdmin):
    list_per_page = 10
```

**Comment by cncert** [comment]
![screenshot_20190307_144343](https://user-images.githubusercontent.com/19517430/53937658-be408300-40e8-11e9-8a35-c4557b5fef17.png)
多谢。
BTW，鼠标放到一行上去，这一行变白了，导致看不清内容，有没有方法变成其他方便查看的颜色?

**Comment by newpanjing** [comment]
你看看是不是自己引入了css，或者是其他开源组件引起的样式冲突？
我这边测试是OK的。
你也可以打开Chrome的控制台，看看是那一句css导致了选中变白色字体。
