### ISSUE TITLE
详情页面返回按钮无效

### ISSUE THREAD

**Issue by OneCat08** [newpanjing/simpleui#101]
1.版本为django-simpleui    2.1.4.619
2.进入详情页，点击返回按钮无任何响应

**Comment by newpanjing** [comment]
我这边测试暂时是没有发现这个问题，你能复述下重现步骤么？

**Comment by OneCat08** [comment]
您好，具体情况如下：
1. 在应用中admin文件内
2.设置应用后台时，若设置 save_on_top = True 则返回按钮会展示在编辑页面的顶部
3.此时顶部的返回按钮则无法起作用




| |
赵腾飞
|
|
邮箱：13021080852@163.com
|

签名由 网易邮箱大师 定制

在2019年06月27日 16:18，Jingle 写道：

我这边测试暂时是没有发现这个问题，你能复述下重现步骤么？

**Comment by OneCat08** [comment]
还存在一个页面适配问题：
当将左侧导航栏收起时，二级目录的图标与标题会错行展示，标题在第一行，图标在第二行；详见附图
使用笔记本为 mac air 13寸浏览器为最新版谷歌浏览器，safari浏览器也是如此。







| |
赵腾飞
|
|
邮箱：13021080852@163.com
|

签名由 网易邮箱大师 定制

在2019年06月27日 16:57，OneCat08 写道：
您好，具体情况如下：
1. 在应用中admin文件内
2.设置应用后台时，若设置 save_on_top = True 则返回按钮会展示在编辑页面的顶部
3.此时顶部的返回按钮则无法起作用




| |
赵腾飞
|
|
邮箱：13021080852@163.com
|

签名由 网易邮箱大师 定制

在2019年06月27日 16:18，Jingle 写道：

我这边测试暂时是没有发现这个问题，你能复述下重现步骤么？
