### ISSUE TITLE
自定义action按钮之后，导致原先所有的action无法显示。

### ISSUE THREAD

**Issue by biancangming** [newpanjing/simpleui#102]
**bug描述**
简单的描述下遇到的bug：
自定义action按钮之后，导致原先所有的action无法显示。
仅在服务器下运行出现，DEBUG模式没有出现

定义代码如下
# # 发表文章
    # def push_article(self, request, queryset):
    #     is_delete = queryset.update(delete='False')
    #     if is_delete == 1:
    #         message_bit = "文章已从删除修改为发表状态"
    #
    #     self.message_user(request, "修改成功：%s" % message_bit)
    #
    # push_article.short_description = "发表文章"
    #
    # actions = [push_article]

**重现步骤**
1.
2.
3.

**环境**

1.操作系统：centos
2.python版本：3.6
3.django版本：2.0.7
4.simpleui版本：2.0.6

**其他描述**

**Comment by newpanjing** [comment]
升级最新版即可，以及修复该问题。
