### ISSUE TITLE
我每次直接从前台跳转到编辑页面时，保存完毕自动返回的页面没有菜单栏

### ISSUE THREAD

**Issue by Abeautifulsnow** [newpanjing/simpleui#105]
**bug描述**
简单的描述下遇到的bug：
我每次直接从前台直接跳转到编辑页面时（不经过后台管理页面），保存完毕自动返回的页面没有菜单栏(左侧以及顶部)，然后我就无法找到任何按钮可以让我返回到站点主页。

**环境**

1.操作系统：
2.python版本：Python3.6.8
3.django版本：django2.1.5
4.simpleui版本：2.1.4.618

**Comment by newpanjing** [comment]
这个不算bug，因为是非法打开的 。
