### ISSUE TITLE
大bug 进入admin页面 或刷新后台管理页面 总会闪出一个很丑的模版渲染页面

### ISSUE THREAD

**Issue by Inseeker** [newpanjing/simpleui#108]
**bug描述**
进入后台管理页面 、刷新后台管理页面 ；总会闪出一个很丑的模版渲染页面

**重现步骤**
1.进入admin页面 活着刷新后台管理页面、
 2.总会闪出一个很丑的模版渲染页面 
3.这是一个巨大的bug 直接就是首页 入口的bug
![屏幕快照 2019-07-05 下午9 44 07](https://user-images.githubusercontent.com/30572306/60727163-da0d4600-9f6f-11e9-9bf3-d057298c0806.png)

**Comment by newpanjing** [comment]
😝这么大个bug，竟然被你发现了。下个版本优化下。
