### ISSUE TITLE
自定义搜索功能不生效

### ISSUE THREAD

**Issue by qylove516** [newpanjing/simpleui#11]
我自定义一个过滤器，放在 list_filter 的列表中，要原生的 admin 下是可以出现过滤的效果，但在 simpleui中过滤数据不生效，我的代码如下：
`

model.py
class Price(models.Model):
name = models.CharField('名称', max_length=64, blank=True, null=True)
num = models.IntegerField('价格', blank=True, null=True)

def __str__(self):
    return self.name

class Meta:
    verbose_name = '价格'
    verbose_name_plural = '价格'
admin.py
from django.contrib import admin
from goods import models

class PriceFilter(admin.SimpleListFilter):
"""
自定义价格过滤器
"""
title = '价格'
parameter_name = 'num'

def lookups(self, request, model_admin):
    return (
        ('0', '高价'),
        ('1', '中价'),
        ('3', '低价'),
    )

def queryset(self, request, queryset):
    if self.value() == '0':
        return queryset.filter(num__gt='555')
    if self.value() == '1':
        return queryset.filter(num__gte='222', num__lte='555')
    if self.value() == '3':
        return queryset.filter(num__lt='222')
class PriceAdmin(admin.ModelAdmin):
list_display = ['name', 'num']
ordering = ['-num']
list_filter = [PriceFilter,]
`
请查看，如果有什么不太清楚我，可以随时@我，谢谢！

**Comment by qylove516** [comment]
> 我自定义一个过滤器，放在 list_filter 的列表中，要原生的 admin 下是可以出现过滤的效果，但在 simpleui中过滤数据不生效，我的代码如下：
> `
> 
> model.py
> class Price(models.Model):
> name = models.CharField('名称', max_length=64, blank=True, null=True)
> num = models.IntegerField('价格', blank=True, null=True)
> 
> def **str**(self):
> return self.name
> 
> class Meta:
> verbose_name = '价格'
> verbose_name_plural = '价格'
> admin.py
> from django.contrib import admin
> from goods import models
> 
> class PriceFilter(admin.SimpleListFilter):
> """
> 自定义价格过滤器
> """
> title = '价格'
> parameter_name = 'num'
> 
> def lookups(self, request, model_admin):
> return (
> ('0', '高价'),
> ('1', '中价'),
> ('3', '低价'),
> )
> 
> def queryset(self, request, queryset):
> if self.value() == '0':
> return queryset.filter(num__gt='555')
> if self.value() == '1':
> return queryset.filter(num__gte='222', num__lte='555')
> if self.value() == '3':
> return queryset.filter(num__lt='222')
> class PriceAdmin(admin.ModelAdmin):
> list_display = ['name', 'num']
> ordering = ['-num']
> list_filter = [PriceFilter,]
> `
> 请查看，如果有什么不太清楚我，可以随时@我，谢谢！

暂时解决的方法,
自定义过滤类加入：lookup_kwarg = '’     属性

**Comment by newpanjing** [comment]
OK，下个版本解决。
