### ISSUE TITLE
二级菜单过多时会显示不全

### ISSUE THREAD

**Issue by WangShuai0413** [newpanjing/simpleui#118]
**bug描述**
简单的描述下遇到的bug：

**重现步骤**
1. 二级菜单过多时
2. 点击一级菜单展开
3. 向下拉拉到最后但是还是没显示完所有的二级菜单

**环境**

1.操作系统：
2.python版本：3.6
3.django版本：1.11.8
4.simpleui版本：最新

**其他描述**

**Comment by newpanjing** [comment]
发个图看看？
