### ISSUE TITLE
django manytomany样式问题

### ISSUE THREAD

**Issue by cpu8802667** [newpanjing/simpleui#120]
**bug描述**
简单的描述下遇到的bug：
manytomany 样式出现下半部分不对齐问题

**重现步骤**
1.默认安装
2.
3.

**环境**

1.操作系统：centos 6.5
2.python版本：3.7
3.django版本：2.1.2
4.simpleui版本：2.5

**其他描述**

**Comment by cpu8802667** [comment]
2.0.8 /django/forms/widgets.py LINE 679:
        context['widget']['attrs']['multiple'] = 'multiple'

2.1 /django/forms/widgets.py LINE 670:
        context['widget']['attrs']['multiple'] = True
是不是因为django上述原因引起的？2.0.8是正常的

**Comment by newpanjing** [comment]
model之类的配置的代码也贴出来看看

**Comment by qq854051086** [comment]
![微信截图_20190718110003](https://user-images.githubusercontent.com/38556416/61425949-35b1d900-a94b-11e9-81d3-2d89e9c2efe9.png)
这个或许也是个问题吧，正常页面上底部的“保存”按钮只有拖动一下浏览器边框才会显示“保存”

**Comment by cpu8802667** [comment]
/static/admin/css/widgets.css
.selector .selector-available select {
    width: 380px;
    height: 17.2em;
}

.selector .selector-chosen select {
    width: 380px;
    height: 21em;
}

/static/admin/css/responsive.css
    .form-row .selector-chosen select[multiple] {
        height: 130px;
        min-height: 0;
    }
    .form-row select[multiple] {
        height: auto;
        min-height: 0;
    }
自己解决了，希望下个版本能彻底解决，问题引起主要是左边比右边多了一个过滤

**Comment by cpu8802667** [comment]
![image](https://user-images.githubusercontent.com/53026387/61427737-d7d4bf80-a951-11e9-9b77-acc0334272fc.png)

**Comment by cpu8802667** [comment]
![image](https://user-images.githubusercontent.com/53026387/61427799-05216d80-a952-11e9-9ad3-583661a639dd.png)

**Comment by cpu8802667** [comment]
感觉manytomany的标题显示没出来
![image](https://user-images.githubusercontent.com/53026387/61427858-431e9180-a952-11e9-9866-21833adee430.png)
