### ISSUE TITLE
SIMPLEUI_HOME_PAGE  为Google链接的时候不能访问显示谷歌页面

### ISSUE THREAD

**Issue by zuoakang** [newpanjing/simpleui#121]
**bug描述**
简单的描述下遇到的bug：

SIMPLEUI_HOME_PAGE  为Google的时候不能访问显示谷歌页面
**重现步骤**
settings增加三个配置
SIMPLEUI_LOGIN_PARTICLES = False
SIMPLEUI_HOME_PAGE = 'http://www.google.com'
SIMPLEUI_HOME_TITLE = 'google'

**环境**

1.操作系统：
2.python版本：2.7.14
3.django版本：1.11.2
4.simpleui版本：0.0.1

**其他描述**
![image](https://user-images.githubusercontent.com/22383362/61545989-3b0e4100-aa7b-11e9-90eb-2110f15044ef.png)

**Comment by newpanjing** [comment]
iframe头限制。自行Google或者百度。
