### ISSUE TITLE
编辑页面默认无法显示保存按钮，页面比例缩放后才能正常

### ISSUE THREAD

**Issue by victor-zhang** [newpanjing/simpleui#122]
**bug描述**
简单的描述下遇到的bug：
编辑页面显示不出来下面的保存按钮，把页面缩放一下就可以了。用的Chrome浏览器

**重现步骤**
1. Chrome浏览器100%缩放比例的情况下，点击任意列表页的ID链接，进入某个编辑页面
2. 编辑页无法看到底部的保存按钮，此时缩放一下浏览器的比例，如缩小为90%或扩大为110%，保存按钮就可以显示出来。

**环境**

1.操作系统：macOS Mojave 10.14.5
2.python版本：3.7.3
3.django版本：2.2.1
4.simpleui版本：2.5

**Comment by newpanjing** [comment]
发个截图看看

**Comment by newpanjing** [comment]
升级至2.6试试。

**Comment by victor-zhang** [comment]
升级2.6后正常了，谢谢


 
---原始邮件---
发件人: "Jingle"<notifications@github.com>
发送时间: 2019年7月22日(星期一) 下午3:32
收件人: "newpanjing/simpleui"<simpleui@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"victor.zhang"<shengli_zhang@qq.com>;
主题: Re: [newpanjing/simpleui] 编辑页面默认无法显示保存按钮，页面比例缩放后才能正常 (#122)



Closed #122.
