### ISSUE TITLE
只能打开第一个同名的子菜单项

### ISSUE THREAD

**Issue by excelwang** [newpanjing/simpleui#124]
**bug描述**
如果打开了下面这个子菜单：
![image](https://user-images.githubusercontent.com/7976028/61760800-48228b80-adff-11e9-8b0f-f369bbb4ebe3.png)
点击下面这个同名子菜单，页面不会刷新。
![image](https://user-images.githubusercontent.com/7976028/61760894-8cae2700-adff-11e9-8552-e772f56cd5e2.png)

**环境**

1.操作系统：
2.python版本：3.6
3.django版本：2.2.3
4.simpleui版本：2.6

**Comment by newpanjing** [comment]
刷新请右键对着标签 会弹出菜单。或者直接F5
多标签页的逻辑就是这样，一个菜单只能打开一个tab

**Comment by excelwang** [comment]
不是打开同个菜单。是打开不同父目录下的同名菜单

**Comment by excelwang** [comment]
请仔细看截图

**Comment by newpanjing** [comment]
了解。后续的版本解决下此问题。
