### ISSUE TITLE
Django administration 字樣以及LOGO修改

### ISSUE THREAD

**Issue by MrFrankLiao** [newpanjing/simpleui#125]
**你希望增加什么功能？**
1. 能夠變更首頁左上方Django administration字樣以及左邊的LOGO

**Comment by victor-zhang** [comment]
Django administrator 字样可以在 admin.py 里设置，例如：
`
admin.site.site_header = '自定义文字'
admin.site.site_title = '自定义文字'
`

至于LOGO可以直接找到路径替换，不过如果settings可配就更好了

**Comment by newpanjing** [comment]
文档中已经注明了。具体可以查看文档。字体样式一类 可以参考重新页面 才有block替换。
