### ISSUE TITLE
快捷菜单布局有空白

### ISSUE THREAD

**Issue by victor-zhang** [newpanjing/simpleui#126]
**bug描述**
简单的描述下遇到的bug：
首页快捷菜单排列中间会空白

![image](https://user-images.githubusercontent.com/3185954/61920067-c9f2f000-af8a-11e9-8542-15cc257d0406.png)

**环境**

1.操作系统：Mac OS
2.python版本：3.7
3.django版本：2.2.1
4.simpleui版本：2.6

**Comment by newpanjing** [comment]
你settings.py中的自定义菜单配置 贴出来看看

**Comment by victor-zhang** [comment]
默认出来的快捷菜单，我没有在settings.py里自定义

**Comment by kelerensheng** [comment]
这个问题我也遇到了，我发现主要是应用名字的换行影响
![image](https://user-images.githubusercontent.com/37256102/62360879-6b121580-b54c-11e9-8f9d-5983eae3710e.png)
