### ISSUE TITLE
菜单栏项要根据权限显示

### ISSUE THREAD

**Issue by lennoo** [newpanjing/simpleui#127]
**你希望增加什么功能？**
1. 现菜单栏根据SIMPLEUI_CONFIG设置显示,能否根据登录用户的权限显示不同的项.比如只有超级用户显示auth/user和auth/group等项

**Comment by newpanjing** [comment]
django admin已有权限功能。请自行查阅django文档。

**Comment by lennoo** [comment]
django是有权限管理,现在只能override模板,采用下列的写法,并不优雅,原是想在setting的menu项配置
`               {% if user.is_superuser %}
                <div>
                  <el-menu-item  @click="openTab(menu_user,1)">
                        <i :class="menu_user.icon"></i>
                        <span slot="title" v-text="menu_user.name"></span>
                    </el-menu-item>
                </div>
                {% endif %}`
