### ISSUE TITLE
list_filter中的datetime字段查询时总是自带+08:00:00时区参数

### ISSUE THREAD

**Issue by kelerensheng** [newpanjing/simpleui#129]
**bug描述**
简单的描述下遇到的bug：
无论settings中的时区设置关闭、打开但时区设置不为东八区（如设置TIME_ZONE为utc或US/Pacific），查询请求附带的参数总是00:00:00+08:00，导致某些情况下连接数据库报错，例如不使用时区，筛选datetime类型字段时数据库会报错 ValueError: MySQL backend does not support timezone-aware datetimes when USE_TZ is False.
![image](https://user-images.githubusercontent.com/37256102/62360690-048cf780-b54c-11e9-9f0d-376f4a1efd84.png)

**重现步骤**
1.settings中设置USE_TZ = False；或settings设置USE_TZ = True，TIME_ZONE = 'US/Pacific'
2.某个模型注册admin时，list_filter添加一个datetime类型字段
3.浏览器打开管理后台，在步骤2模型的管理界面选择datetime类型字段的筛选，此时可看到控制台的查询参数为【所选时间 00:00:00+08:00】
4、此时若设置USE_TZ = False，将会报错ValueError: MySQL backend does not support timezone-aware datetimes when USE_TZ is False

**环境**

1.操作系统：centos7
2.python版本：3.7
3.django版本：2.2
4.simpleui版本：2.6

**其他描述**
     没有在simpleui的文档中看到有对此的说明，故不知是否有可以设置datetime字段查询时区的选项，感觉datetime字段的filter应该根据settings中时区设置来确定request中查询参数的时区信息，而不是始终都是00:00:00+08:00。
    第一次提交issue，如有不妥的地方，还望见谅 : )

**Comment by kelerensheng** [comment]
看了下模版源文件，好像就是写死的，暂时手动删除时区信息解决

**Comment by newpanjing** [comment]
之前的版本没考虑时区问题，将在后续的版本处理这个问题。
