### ISSUE TITLE
表格列显示不全

### ISSUE THREAD

**Issue by victor-zhang** [newpanjing/simpleui#130]
**bug描述**
表格右侧部分列显示不出来，好像被盖住了，但右侧是有展示空间的，如下图1，但有些表格就可以显示全，如图2
![image](https://user-images.githubusercontent.com/3185954/62527464-c35b5700-b86d-11e9-85f8-5f80c3be7426.png)

![image](https://user-images.githubusercontent.com/3185954/62597437-a92a8300-b918-11e9-811d-1f8ba9377e50.png)

**环境**

1.操作系统：Mac OS
2.python版本：3.7
3.django版本：2.2.1
4.simpleui版本：2.6

**Comment by haiziming** [comment]
这个我在本地测试ok 的，在生产环境上测试就会出现你这个问题。

**Comment by 1024tianya** [comment]
报错信息 贴一下
