### ISSUE TITLE
django-import-export导入数据时页面边界溢出问题

### ISSUE THREAD

**Issue by biancangming** [newpanjing/simpleui#134]
**bug描述**
简单的描述下遇到的bug：
导入时确认导入页面，数据过长出现溢出
![image](https://user-images.githubusercontent.com/42108047/63327083-21089c80-c360-11e9-95b5-f66721dd65bf.png)

**重现步骤**

![image](https://user-images.githubusercontent.com/42108047/63327173-4b5a5a00-c360-11e9-9779-e2a6c4ccbb9b.png)

**环境**

1.操作系统：
2.python版本：
3.django版本：
4.simpleui版本：

**其他描述**

**Comment by newpanjing** [comment]
了解，下个版本修复。
