### ISSUE TITLE
希望使用elementui标准方式来实现search-form中的filter选项

### ISSUE THREAD

**Issue by killer0217** [newpanjing/simpleui#137]
**你希望增加什么功能？**
1.希望使用elementui标准方式来实现search-form中的filter选项
这样有助于改成可以级联过滤

**留下你的联系方式，以便与你取得联系**
QQ：群中（我是一个存在） 304287159

**Comment by newpanjing** [comment]
在即将发布的simple pro版中以element-ui标准的方式实现了。敬请期待

**Comment by newpanjing** [comment]
该功能已经在simplepro中得到支持。

官网：
[https://simpleui.88cto.com/simplepro](https://simpleui.88cto.com/simplepro)

SimplePro主页：
[https://github.com/newpanjing/simplepro](https://github.com/newpanjing/simplepro)

论坛：

[https://simpleui.88cto.com/](https://simpleui.88cto.com/)
