### ISSUE TITLE
admin中设置fieldsets的样式无效

### ISSUE THREAD

**Issue by sufedonoho** [newpanjing/simpleui#138]
**bug描述**
简单的描述下遇到的bug：
在admin中设置了fieldsets的样式classes属性，但是没有变化，被simpleui的样式干掉了
同样的，在fieldsets中设置两个元素在一行也会出现bug

**重现步骤**
@admin.register(ItemBasicInfo)
class ItemBasicInfoAdmin(ImportExportActionModelAdmin):
    fieldsets = [
                    (
                        '项目基础信息', {
                            'fields': [
                                ('number', 'green_path', 'duty_director'), ('nature', 'name'), ('department', 'manager'), ('compliance', 'risk'), ('green_start_time', 'enter_rm_time')],
                            'classes': ('collapse',),
                        }),
                    (
                        '项目基本交易要素', {
                            'fields': [
                                ('inv_fin_class', 'check_amount'), ('trust_return', 'actual_controller1'), ('controller1_proportion','is_structure'), ('deal_attribute', 'deal_form'), ('province', 'city', 'district')],
                            'classes': ('collapse',),
                        }),
                    (
                        '项目风险政策要素', {
                            'fields': [
                                ('category', 'region_level', 'controller_rank'), ('industry_status', 'estate_business_type',  'estate_risk_policy'), ('public_region_level', 'public_risk_policy'), ('consume_risk_policy', 'supply_risk_policy')],
                            'classes': ('collapse',),
                        }),
                    (
                        '项目评价', {
                            'fields': [
                                ('review_authority', 'item_stage'), ('diligence_report_score', 'diligence_report_evaluation'),('intermediary_score', 'intermediary_evaluation'), ('is_meeting','is_many_meetings', 'meeting_times', 'first_meeting_result', 'last_meeting_result')
                            ],
                            'classes': ('collapse',),
                        }
                    )
]

![image](https://user-images.githubusercontent.com/34481211/63583701-181d0280-c5ce-11e9-828b-a34440344fb2.png)

**环境**

1.操作系统：
2.python版本：3.6.6
3.django版本：2.2.4
4.simpleui版本：2.7

**其他描述**

**Comment by newpanjing** [comment]
classes 是会在你的元素上增加class，需要自己引入样式表。
