### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by afansv** [newpanjing/simpleui#139]
Please, add an english language support

**Comment by newpanjing** [comment]
Hello, switch django default language to support English.

**Comment by afansv** [comment]
And what about readme and docs?

**Comment by newpanjing** [comment]
English version readme：
See link:
[https://github.com/newpanjing/simpleui/blob/master/doc/en/README_en.md](https://github.com/newpanjing/simpleui/blob/master/doc/en/README_en.md)
