### ISSUE TITLE
页面编辑链接建意新开页面显示

### ISSUE THREAD

**Issue by JohnYan2017** [newpanjing/simpleui#140]
希望能改成或增加配置项, 实现点击链接后进入的编辑页是新开窗口或在新的页显示
![image](https://user-images.githubusercontent.com/30788736/63992113-f0252600-cb1c-11e9-9458-4b37f250a188.png)

因为如果不这样, 进入编辑后, 保存会回到模块清单, 而不是回到父清单

**Comment by newpanjing** [comment]
可以自行参照django文档写，django已经提供了自定义功能。
