### ISSUE TITLE
建议自定义菜单添加将自定义app的菜单，可以将app作为子菜单项的功能，现在只能自定义models的菜单

### ISSUE THREAD

**Issue by Licooooooool** [newpanjing/simpleui#141]

**Comment by newpanjing** [comment]
请详细描述下。

**Comment by Licooooooool** [comment]
您好！具体就是比如说有创建6个app,现在的版本就会在菜单上直接显示出来6个功能及他们的models（算是子菜单吧），但如果要是这6个app有3种不同的类型，想将其归类并分至3个父功能下，页面是也只显示这三个大的功能项，大的功能项的子菜单项才是这些app，现在只有两层菜单，能否加一个父级菜单来归类apps，或者自定义菜单结构的功能呢
