### ISSUE TITLE
希望能加上支持图表的功能，后台管理一般都是需要图表的支持的

### ISSUE THREAD

**Issue by shangzekai** [newpanjing/simpleui#143]
**你希望增加什么功能？**
1. 图表的支持

**你希望哪些方面得到优化？**
1. 表格可以支持导出数据

**留下你的联系方式，以便与你取得联系**
QQ：493133139

**Comment by newpanjing** [comment]
在即将发布的simple pro版中增加了图表。敬请期待

**Comment by newpanjing** [comment]
该功能已经在simplepro中得到支持。

官网：
[https://simpleui.88cto.com/simplepro](https://simpleui.88cto.com/simplepro)

SimplePro主页：
[https://github.com/newpanjing/simplepro](https://github.com/newpanjing/simplepro)

论坛：

[https://simpleui.88cto.com/](https://simpleui.88cto.com/)
