### ISSUE TITLE
首页白板

### ISSUE THREAD

**Issue by victor-zhang** [newpanjing/simpleui#144]
**bug描述**
登录后首页白板（空白，没有任何信息），使用django-admin原生就可以正常显示列表。浏览器报javascript错误，如截图。

**环境**
1.操作系统：CentOS7
2.python版本：3.7.4
3.django版本：2.2.0
4.simpleui版本：2.8
<img width="1281" alt="屏幕快照 2019-09-03 下午12 46 06" src="https://user-images.githubusercontent.com/3185954/64144847-f121c480-ce48-11e9-96d0-58917ae442c5.png">

**Comment by newpanjing** [comment]
重新安装django-simpleui，然后清理缓存，克隆静态。

**Comment by victor-zhang** [comment]
> 重新安装django-simpleui，然后清理缓存，克隆静态。

按这个方法也没用，登录界面和其他子页面正常，就是首页不行，估计是我的首页内容多触发了某个bug

**Comment by newpanjing** [comment]
缓存问题，重新克隆下静态文件，清理下浏览器缓存。

**Comment by victor-zhang** [comment]
我上次是pip uninstall django-simpleui，然后又 pip install django-simpleui，并清空浏览器缓存。还是不行。 你是说我需要clone代码后把 static 目录单独替换一下 python3.7/site-packages/simpleui/static ？

**Comment by newpanjing** [comment]
python3 manage.py collectstatic

**Comment by victor-zhang** [comment]
刚试了，不行啊

**Comment by f2m4** [comment]
刚才我也白屏.删除静态文件.shift+f5刷新一下.ok了.
