### ISSUE TITLE
自定义应用名称无效？

### ISSUE THREAD

**Issue by danvinhe** [newpanjing/simpleui#146]
**bug描述**
注册model后，后台展示的应用名称是Otc，不知道怎么修改。试了下设置应用的verbose_name,但没有生效

**重现步骤**
class OtcConfig(AppConfig):
    name = 'otc'
    verbose_name = '场外交易'

**环境**

1.操作系统：macOs
2.python版本：3.6.7
3.django版本：2.2
4.simpleui版本：最新

**其他描述**

**Comment by 1024tianya** [comment]
这个不是bug  在你的 app 初始化文件中加入default_app_config 你写错了

**Comment by Deali-Axy** [comment]
> 这个不是bug 在你的 app 初始化文件中加入default_app_config 你写错了

能介绍清楚一点如何操作吗?
