### ISSUE TITLE
无法关闭所有的tab标签，最有一个无法关闭

### ISSUE THREAD

**Issue by liuts** [newpanjing/simpleui#149]
**bug描述**
简单的描述下遇到的bug：
无法关闭所有的tab标签（最后一个tab无法关闭）
![image](https://user-images.githubusercontent.com/8000832/64579187-8cb8b500-d3b4-11e9-94c0-019c3aefc88b.png)

**重现步骤**
1.打开2个以上的tab，然后依次关闭，最后一个无法关闭
2.
3.

**环境**

1.操作系统：
2.python版本：3.7
3.django版本：2.1.12
4.simpleui版本：3.9

**其他描述**

**Comment by shylocks** [comment]
遇到了同样的问题，临时解决方案：
将..\site-packages\simpleui\static\admin\simpleui-x\js\index.js 中 changeUrl 函数替换为
```javascript
function changeUrl(data) {
        location.href = '#' + (data.url || '/')
}
```

**Comment by liuts** [comment]
好的。多谢。

**Comment by liuwei563142075** [comment]
在simpleui/static/admin/simpleui-x/js/index.js中找到changeUrl(data)方法如下：
“”“
function changeUrl(data) {
        if (data.url.indexOf('http') != 0) {
                location.href = '#' + (data.url || '/')
           }
    }
”“”

修改为：
“”“
function changeUrl(data) {
        if (data.url) {
            if (data.url.indexOf('http') != 0) {
                location.href = '#' + (data.url || '/')
            }
        }
    }
”“”
即可解决该问题

**Comment by newpanjing** [comment]
> 在simpleui/static/admin/simpleui-x/js/index.js中找到changeUrl(data)方法如下：
> “”“
> function changeUrl(data) {
> if (data.url.indexOf('http') != 0) {
> location.href = '#' + (data.url || '/')
> }
> }
> ”“”
> 
> 修改为：
> “”“
> function changeUrl(data) {
> if (data.url && data.url.indexOf('http') != 0) {
> location.href = '#' + (data.url || '/')
> }
> }
> ”“”
> 即可解决该问题

老铁 你应该push下代码来simpleui的dev分支呀，我就不改了，哈哈。

**Comment by mufengcoding** [comment]
> > 在simpleui/static/admin/simpleui-x/js/index.js中找到changeUrl(data)方法如下：
> > “”“
> > function changeUrl(data) {
> > if (data.url.indexOf('http') != 0) {
> > location.href = '#' + (data.url || '/')
> > }
> > }
> > ”“”
> > 修改为：
> > “”“
> > function changeUrl(data) {
> > if (data.url && data.url.indexOf('http') != 0) {
> > location.href = '#' + (data.url || '/')
> > }
> > }
> > ”“”
> > 即可解决该问题
> 
> @liuwei563142075
> 老铁 你应该push下代码来simpleui的dev分支呀，我就不改了，哈哈。

应该是主线就是这样的我也遇到了
