### ISSUE TITLE
后台列表页的table 能否增加固定列的功能

### ISSUE THREAD

**Issue by zzzdtz** [newpanjing/simpleui#150]
**你希望增加什么功能？**
1. 建议增加列表页的table 在列特别多的情况下，增加固定第一列 或者 最后一列的功能

**Comment by newpanjing** [comment]
在即将推出的simpleui pro 会增加固定列的支持。

**Comment by newpanjing** [comment]
该功能已经在simplepro中得到支持。

官网：
[https://simpleui.88cto.com/simplepro](https://simpleui.88cto.com/simplepro)

SimplePro主页：
[https://github.com/newpanjing/simplepro](https://github.com/newpanjing/simplepro)

论坛：

[https://simpleui.88cto.com/](https://simpleui.88cto.com/)
