### ISSUE TITLE
怎么设置使用左侧栏的页面定制

### ISSUE THREAD

**Issue by xx-zhang** [newpanjing/simpleui#151]
请问下，集成 admin/index.html 或者 admin/base_site.html 的方法。
也就是说 如果要使用自定义的页面保留左侧的栏目，应该怎么弄

我已经尝试过直接extends 但是 一直loads-memus错误，但是加载了 simple-ui-tags 仍然报错。百思不得其解。

**你希望哪些方面得到优化？**
1.
2.
3.

**留下你的联系方式，以便与你取得联系**
QQ：xxxxx
邮箱：xxx@xxx.com

**Comment by newpanjing** [comment]
参考文档自定义菜单
