### ISSUE TITLE
无法使用 django-import-export 来实现导入导出功能

### ISSUE THREAD

**Issue by laolu94678** [newpanjing/simpleui#152]
**bug描述**
简单的描述下遇到的bug：

**重现步骤**
1. 安装并配置 django-import-export
2. 打开管理后台
3. 没有导入和导出按钮

**环境**

1.操作系统：
2.python版本：3.7
3.django版本：2.2.5
4.simpleui版本：2.8

**其他描述**
麻烦大佬看一下 , 如何使用django-import-export 来实现导入导出功能

**Comment by newpanjing** [comment]
参照demo：[https://github.com/newpanjing/simpleui_demo](https://github.com/newpanjing/simpleui_demo)

**Comment by mufengcoding** [comment]
这个不能算bug吧，兄台没有好好看文档啊

**Comment by laolu94678** [comment]
的确疏忽了 , 感谢
