### ISSUE TITLE
只剩一个tab页的时候无法关闭，并没有提示

### ISSUE THREAD

**Issue by mufengcoding** [newpanjing/simpleui#153]
**bug描述**
简单的描述下遇到的bug：

**重现步骤**
1.打开一个tab页
![image](https://user-images.githubusercontent.com/13534743/64939061-8df55080-d892-11e9-8ada-ea2330bbdae1.png)
发现关不了
2.再打开一个tab页
![image](https://user-images.githubusercontent.com/13534743/64939090-a36a7a80-d892-11e9-9d22-cf101b38b6e2.png)
可以关闭第一个

**环境**

1.操作系统：
2.python版本：3.6
3.django版本：2.2
4.simpleui版本：2.9

**其他描述**
无

**Comment by xx-zhang** [comment]
是啊， 而且应该在最前面增加一个删除所有tab的按钮，我编辑 inder.html 改了下，总是出错，因为vue.js真是玩不转。
