### ISSUE TITLE
自定义按钮问题。action_type=1 和 action_type=2 一样。

### ISSUE THREAD

**Issue by xx-zhang** [newpanjing/simpleui#154]
**bug描述**
简单的描述下遇到的bug：

**重现步骤**
1. 如同demo一样， 这里 action_type=1和action_type=2测试。
![image](https://user-images.githubusercontent.com/47806549/65003536-80d87000-d92b-11e9-94a0-07f3bedb405f.png)

2. 直接打开页面，发现 action_type=1 并没有在当前tab的右侧创建。
3. 后来我查看源码 `admin/actions.html`，看了下 action_type=1 的代码，确实用的是 paremnt.window.app.openTab ;
于是我自己也用了下。发现并没有在当前跳转。
![image](https://user-images.githubusercontent.com/47806549/65003419-04de2800-d92b-11e9-8430-58eecb84a25f.png)

**环境**

1.操作系统：
2.python版本：368
3.django版本：217
4.simpleui版本：29

**其他描述**
推荐出一个能够支持 url 传递参数，tab打开的可用base模板的示例。我也在群里，昨天群主告诉我，可以用opentab或者自定义按钮，今天尝试了下，再提个issue

**Comment by newpanjing** [comment]
经测试，1、2打开是正常的，请检查是否有缓存。至于参数 可考虑在后续版本中实现。
