### ISSUE TITLE
context_processors自定义模板功能和simpleui冲突了

### ISSUE THREAD

**Issue by JacksBW** [newpanjing/simpleui#156]
**bug描述**
简单的描述下遇到的bug：

**重现步骤**
1. 我在settings.py里添加了context_processors会导致admin一片空白

**环境**

1.操作系统：
2.python版本：3.7
3.django版本：最新版
4.simpleui版本：最新版

**其他描述**
我在settings.py里添加了context_processors会导致admin的整个页面一片空白,但是都没有报错,如果我不使用context_processors来自定义模板,admin就会正常显示,但是前端页面我就没办法使用公共参数渲染了

**Comment by xx-zhang** [comment]
试试django的小版本看看 比如 2.0.12, 2.1.7
