### ISSUE TITLE
自定义的简易页面继承 admin/base_site.html ，样式与admin 其他页面差异大

### ISSUE THREAD

**Issue by cooleasyhan** [newpanjing/simpleui#157]
**你希望增加什么功能？**
1. 提供一个用于自定义页面继承的模板，用于简易页面开发， 界面只包含一些信息提示，加上数个字段的Form，几个提交按钮，而没有DB model

**Comment by newpanjing** [comment]
这个不属于框架范围，暂时不予以采纳。
