### ISSUE TITLE
将外键的时间加入filter时出错，不显示Filter栏

### ISSUE THREAD

**Issue by killer0217** [newpanjing/simpleui#158]
**bug描述**
简单的描述下遇到的bug：

将外键的时间加入filter时出错，不显示Filter栏

在search_form.html模板中   v-model中应该用spec.field_path而不是 spec.field.name
 <el-date-picker class="simpleui-form-item"
                                    v-model="{{ spec.field_path }}"
                                    @change="change{{ spec|get_date_type|capfirst }}"
                                    type="{{ spec|get_date_type }}range"
                                    start-placeholder="{{ spec.title }}"
                                    end-placeholder="{{ spec.title }}">
                            </el-date-picker>
同时需要修改
simpletags.py中的
            if field_type:
                data[spec.field_path] = field_type

否则就会出现 “将外键的时间加入filter时出错，不显示Filter栏”

**Comment by newpanjing** [comment]
下个版本修复。
