### ISSUE TITLE
案例

### ISSUE THREAD

**Issue by newpanjing** [newpanjing/simpleui#16]
这里提交案例：
格式：
名字：xxx网站或公司
网址：github.com
Logo: http://xxx.com/123.png

**Comment by a1401358759** [comment]
名字：杨学峰博客
网址：https://yangsihan.com
logo：https://yangsihan.com/static/css/logo.png

**Comment by fabiocaccamo** [comment]
I recommend a better theme: https://github.com/fabiocaccamo/django-admin-interface
or pip install:
`pip install django-admin-interface`

**Comment by Czj1997-02** [comment]
名字：混沌框架
网址：hundun.ink
Logo: https://www.hundun.ink/media/logo.png
