### ISSUE TITLE
冻结头部/首列/尾列

### ISSUE THREAD

**Issue by wahello** [newpanjing/simpleui#160]
**你希望增加什么功能？**
1.冻结头部, 首列或多列, 尾列或多列

**留下你的联系方式，以便与你取得联系**
QQ：xxxxx
邮箱：xxx@xxx.com

**Comment by newpanjing** [comment]
pro版 已经支持，即将发布。敬请期待。

**Comment by newpanjing** [comment]
该功能已经在simplepro中得到支持。

官网：
[https://simpleui.88cto.com/simplepro](https://simpleui.88cto.com/simplepro)

SimplePro主页：
[https://github.com/newpanjing/simplepro](https://github.com/newpanjing/simplepro)

论坛：

[https://simpleui.88cto.com/](https://simpleui.88cto.com/)
