### ISSUE TITLE
给自定义按钮增加二次确认信息展示框

### ISSUE THREAD

**Issue by SlovEnt** [newpanjing/simpleui#166]
**你希望哪些方面得到优化？**
1.自定义按钮时，点击以后，在触发事件前，给予信息提示框。比如，点击“复制员工”按钮后，弹出提示框“是否复制该员工信息（Y/N）”。

**留下你的联系方式，以便与你取得联系**
QQ：6929962

**Comment by glaye** [comment]
关注
