### ISSUE TITLE
新增页面返回错误

### ISSUE THREAD

**Issue by izqutcom** [newpanjing/simpleui#168]
**bug描述**
简单的描述下遇到的bug：新增页面返回错误。

**重现步骤**
1. 点击新增按钮
2. 点击返回

**环境**

1.操作系统：
2.python版本：3.7.3
3.django版本：2.2.5
4.simpleui版本：3.1

**其他描述**

**Comment by newpanjing** [comment]
升级到3.2即可，修复了该bug。
