### ISSUE TITLE
快速点击返回，内容区域会闪烁出现菜单栏后消失

### ISSUE THREAD

**Issue by liuwei563142075** [newpanjing/simpleui#171]
**bug描述**
简单的描述下遇到的bug：

**重现步骤**
1.登入系统
2.点击用户管理-》点击新增用户-》点击返回
3.快速重复2步骤，会在内容区域闪烁出现菜单栏

**环境**

1.操作系统：Windows10
2.python版本：3.7.1
3.django版本：2.2.5
4.simpleui版本：2.9

**其他描述**

**Comment by liuwei563142075** [comment]
![图片](https://user-images.githubusercontent.com/40060336/67183565-5d19b580-f414-11e9-9e1e-7cb7a34490e4.png)

**Comment by liuwei563142075** [comment]
![图片](https://user-images.githubusercontent.com/40060336/67183885-18424e80-f415-11e9-95eb-e19db7dc0548.png)

**Comment by liuwei563142075** [comment]
![图片](https://user-images.githubusercontent.com/40060336/67183998-4b84dd80-f415-11e9-91b1-d5b48846a907.png)

**Comment by newpanjing** [comment]
升级到3.2 也就是最新版就可以了。

发自我的iPhone

**Comment by liuwei563142075** [comment]
thank you.

------------------ 原始邮件 ------------------
发件人: "Jingle"<notifications@github.com>;
发送时间: 2019年10月21日(星期一) 晚上11:12
收件人: "newpanjing/simpleui"<simpleui@noreply.github.com>;
抄送: "刘呆哗"<563142075@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [newpanjing/simpleui] 快速点击返回，内容区域会闪烁出现菜单栏后消失 (#171)



升级到3.2 也就是最新版就可以了。
 
 发自我的iPhone

**Comment by liuwei563142075** [comment]
我已经更新到最新版本3.2，但是依旧出现了这个问题，github上提供的demo上登陆不进去，我也不能在上面进行测试。

**Comment by newpanjing** [comment]
请更新至3.4

**Comment by liuwei563142075** [comment]
ok，我已更新，这个问题已经解决，谢谢您



---原始邮件---
发件人: "Jingle"<notifications@github.com&gt;
发送时间: 2019年11月18日(星期一) 中午1:26
收件人: "newpanjing/simpleui"<simpleui@noreply.github.com&gt;;
抄送: "liuwei"<563142075@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [newpanjing/simpleui] 快速点击返回，内容区域会闪烁出现菜单栏后消失 (#171)



请更新至3.4
