### ISSUE TITLE
pro 建议增加页面编辑

### ISSUE THREAD

**Issue by hublive** [newpanjing/simpleui#172]
![image](https://user-images.githubusercontent.com/37129638/67481379-7c267a80-f694-11e9-9c7c-9daa0346645e.png)

![image](https://user-images.githubusercontent.com/37129638/67481430-982a1c00-f694-11e9-91c5-0e227c2e54c7.png)

![image](https://user-images.githubusercontent.com/37129638/67481565-cc9dd800-f694-11e9-87d0-4ad866eca82d.png)

**Comment by newpanjing** [comment]
下个版本考虑增加此功能

**Comment by newpanjing** [comment]
pro升级到最新版，已经支持编辑，开启list_editable后，双击进入编辑。
