### ISSUE TITLE
simpletags is not a  valid tag library

### ISSUE THREAD

**Issue by SuperChenXin** [newpanjing/simpleui#175]
**bug描述**
简单的描述下遇到的bug：

`TemplateSyntaxError at /admin/
'simpletags' is not a valid tag library: ImportError raised loading simpleui.templatetags.simpletags: No module named 'django.urls'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/
Django Version:	1.8.2
Exception Type:	TemplateSyntaxError
Exception Value:	
'simpletags' is not a valid tag library: ImportError raised loading simpleui.templatetags.simpletags: No module named 'django.urls'
Exception Location:	/home/ubuntu/.virtualenvs/test2/lib/python3.7/site-packages/django/template/defaulttags.py in load, line 1163
Python Executable:	/home/ubuntu/.virtualenvs/bj21/bin/python
Python Version:	3.7.5
Python Path:	
['/home/ubuntu/bj21',
 '/home/ubuntu/.virtualenvs/test2/lib/python37.zip',
 '/home/ubuntu/.virtualenvs/test2/lib/python3.7',
 '/home/ubuntu/.virtualenvs/test2/lib/python3.7/lib-dynload',
 '/usr/lib/python3.7',
 '/home/ubuntu/.virtualenvs/test2/lib/python3.7/site-packages']
Server time:	星期四, 7 十一月 2019 09:24:03 +0800`

**环境**

1.操作系统：ubuntu
2.python版本：3.7
3.django版本：
4.simpleui版本：

**其他描述**

**Comment by fandsimple** [comment]
> **bug描述**
> 简单的描述下遇到的bug：
> 
> `TemplateSyntaxError at /admin/ 'simpletags' is not a valid tag library: ImportError raised loading simpleui.templatetags.simpletags: No module named 'django.urls' Request Method: GET Request URL: http://127.0.0.1:8000/admin/ Django Version: 1.8.2 Exception Type: TemplateSyntaxError Exception Value: 'simpletags' is not a valid tag library: ImportError raised loading simpleui.templatetags.simpletags: No module named 'django.urls' Exception Location: /home/ubuntu/.virtualenvs/test2/lib/python3.7/site-packages/django/template/defaulttags.py in load, line 1163 Python Executable: /home/ubuntu/.virtualenvs/bj21/bin/python Python Version: 3.7.5 Python Path: ['/home/ubuntu/bj21', '/home/ubuntu/.virtualenvs/test2/lib/python37.zip', '/home/ubuntu/.virtualenvs/test2/lib/python3.7', '/home/ubuntu/.virtualenvs/test2/lib/python3.7/lib-dynload', '/usr/lib/python3.7', '/home/ubuntu/.virtualenvs/test2/lib/python3.7/site-packages'] Server time: 星期四, 7 十一月 2019 09:24:03 +0800`
> 
> **环境**
> 
> 1.操作系统：ubuntu
> 2.python版本：3.7
> 3.django版本：
> 4.simpleui版本：
> 
> **其他描述**

同样遇到这样的问题，你是怎么解决的

**Comment by NaNShaner** [comment]
> > **bug描述**
> > 简单的描述下遇到的bug：
> > `TemplateSyntaxError at /admin/ 'simpletags' is not a valid tag library: ImportError raised loading simpleui.templatetags.simpletags: No module named 'django.urls' Request Method: GET Request URL: http://127.0.0.1:8000/admin/ Django Version: 1.8.2 Exception Type: TemplateSyntaxError Exception Value: 'simpletags' is not a valid tag library: ImportError raised loading simpleui.templatetags.simpletags: No module named 'django.urls' Exception Location: /home/ubuntu/.virtualenvs/test2/lib/python3.7/site-packages/django/template/defaulttags.py in load, line 1163 Python Executable: /home/ubuntu/.virtualenvs/bj21/bin/python Python Version: 3.7.5 Python Path: ['/home/ubuntu/bj21', '/home/ubuntu/.virtualenvs/test2/lib/python37.zip', '/home/ubuntu/.virtualenvs/test2/lib/python3.7', '/home/ubuntu/.virtualenvs/test2/lib/python3.7/lib-dynload', '/usr/lib/python3.7', '/home/ubuntu/.virtualenvs/test2/lib/python3.7/site-packages'] Server time: 星期四, 7 十一月 2019 09:24:03 +0800`
> > **环境**
> > 1.操作系统：ubuntu
> > 2.python版本：3.7
> > 3.django版本：
> > 4.simpleui版本：
> > **其他描述**
> 
> 同样遇到这样的问题，你是怎么解决的

看看你的simpleui的安装目录下面有没有这个目录
![image](https://user-images.githubusercontent.com/20882547/78367430-a80b3c00-75f4-11ea-9f01-d2aaf4299781.png)
