### ISSUE TITLE
克隆静态文件到根目录问题

### ISSUE THREAD

**Issue by Lucius-chen** [newpanjing/simpleui#177]
**bug描述**
setting中如添加以下配置：
STATIC_ROOT = os.path.join(BASE_DIR, "static")
再次启动项目会报错：
ERRORS:
?: (staticfiles.E002) The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting.
应该为：
STATIC_ROOT = os.path.join(BASE_DIR, "/static/")

**Comment by newpanjing** [comment]
请看django文档。
