### ISSUE TITLE
admin页面两个小建议

### ISSUE THREAD

**Issue by biancangming** [newpanjing/simpleui#178]
**你希望增加什么功能？**
1.可以自定义admin页面的favicon.ico
2. 在没有定义筛选项的时候，隐藏搜索显示按钮。
![https://simpleui.88cto.com/media/uploads/forum/files/Jljwu5Em.png](https://simpleui.88cto.com/media/uploads/forum/files/Jljwu5Em.png)

**Comment by newpanjing** [comment]
OK 下个版本优化
