### ISSUE TITLE
使用django-import-export 功能的时候有错

### ISSUE THREAD

**Issue by zengbiao** [newpanjing/simpleui#181]
**bug描述**
简单的描述下遇到的bug：
在python3.8 环境
使用导出功能的时候遇到在django options.py  if action_form.is_valid() 里检查有报错
errors内容是: 这个字段是必须项
**重现步骤**
1.
2.
3.

**环境**

1.操作系统：windows10
2.python版本：3.8
3.django版本：2.2.7
4.simpleui版本：当前最新

**其他描述**

**Comment by zengbiao** [comment]
VM377 action_formats.js:2 Uncaught TypeError: $ is not a function
    at VM377 action_formats.js:2
    at VM377 action_formats.js:22
看起来是js的问题

**Comment by zengbiao** [comment]
解决了，在actions.html  改成这样：name="action" value="export_admin_action"

**Comment by newpanjing** [comment]
好的谢谢，我下次验证下这个问题。
