### ISSUE TITLE
自定义actions提示未选择动作

### ISSUE THREAD

**Issue by liyizhecn** [newpanjing/simpleui#182]
**bug描述**
admin 里自定义 actions 后，操作该动作时提示未选择动作
取消配置simpleui后正常

**重现步骤**
```
@admin.register(System)
class SystemAdmin(admin.ModelAdmin):
    list_display = ('id', 'name')
    search_fields = ('name', )
    actions = ['message_test']
    def message_test(self, request, queryset):
        messages.add_message(request, messages.SUCCESS, '操作成功123123123123')
```

**环境**

1.操作系统：macOS
2.python版本：Python 3.6.8
3.django版本：Django==2.2.7
4.simpleui版本：django-simpleui==3.4

**其他描述**

**Comment by newpanjing** [comment]
近期修复该问题。

**Comment by liyizhecn** [comment]
该功能目前在哪个版本可以使用，我暂时回退一下
自定义actions是目前我的项目中使用较重的一个功能，谢谢

**Comment by liyizhecn** [comment]
> 近期修复该问题。
> […](#)

该功能目前在哪个版本可以使用，我暂时回退一下
自定义actions是目前我的项目中使用较重的一个功能，谢谢

**Comment by newpanjing** [comment]
回退3.3试试

**Comment by liyizhecn** [comment]
> 回退3.3试试
> […](#)

3.3该功能正常 谢谢大佬 😺
