### ISSUE TITLE
使用 simpleui 后, collectstatic 出现大量异常输出

### ISSUE THREAD

**Issue by lowmanisbusy** [newpanjing/simpleui#183]
**bug描述**
简单的描述下遇到的bug：
         使用 pip install 的方式安装的 simpleui, 然后每次 python manage.py collectstatic 时, 会出现大量的异常标准输出, 类似如下:

If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/img/tooltag-arrowright.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/img/README.txt'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/img/icon-unknown.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/img/LICENSE'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/img/icon-deletelink.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/img/sorting-icons.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/img/icon-unknown-alt.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/img/icon-addlink.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/img/inline-delete.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/img/gis/move_vertex_on.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/img/gis/move_vertex_off.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

**重现步骤**
1.pip install simpleui
2.python manage.py collectstatic
3.

**环境**

1.操作系统：
2.python版本：3.6.8
3.django版本：2.1.7
4.simpleui版本：django-simpleui==3.1

**其他描述**

**Comment by lowmanisbusy** [comment]
确定是安装了 simpleui 才导致的这个问题, 取消 app 注册以后, 异常消失

**Comment by newpanjing** [comment]
这种问题都不想回复了，请自行查阅django文档。关于静态文件的，谢谢。
