### ISSUE TITLE
初次体验，界面和功能很友好，但是遇到了个显示上的小问题

### ISSUE THREAD

**Issue by thep0y** [newpanjing/simpleui#184]
上图：
[https://upload-images.jianshu.io/upload_images/8687256-865b31a1037e2244.png](url)

**设备信息**
OS: macOS 10.14.6
浏览器：Safari、Firfox 和 Chrome都这样

**处理方式**
不知道此问题是否普遍。经测试，取消changelists.css里第79行input的padding后文字位置就正常了

**留下你的联系方式，以便与你取得联系**
QQ：xxxxx
邮箱：thepoy@163.com

**Comment by newpanjing** [comment]
好的，你也可以创建一个Pull Request将你修改的代码合并到dev分支。
