### ISSUE TITLE
外键的to参数指定为代理模型时候，ModelAdmin中list_filter配置的筛选字段失效（不显示）

### ISSUE THREAD

**Issue by finlu** [newpanjing/simpleui#185]
**bug描述**
简单的描述下遇到的bug：
我在一个模型中把另一个模型作为外键，但是to字段指定的是一个代理模型。django是支持将外键的to字段指定为代理模型的，而且在xadmin中配置list_filter也会生效，但是这个项目中配置了就不显示该外键字段。

**Comment by newpanjing** [comment]
贴下具体的配置代码？

**Comment by finlu** [comment]
admin.py:
@admin.register(ExpertComment)
class ExpertCommentAdmin(admin.ModelAdmin):
    list_filter = ['expert', ]

models.py:
class Expert(User):
    class Meta:
        proxy = True

class ExpertComment(models.Model):
    expert = models.ForeignKey(to='oauth.Expert', on_delete=models.CASCADE)

具体配置是这样的，但是admin后台界面上不会显示根据export字段进行搜索的下拉框。

**Comment by finlu** [comment]
admin.py:
`python
@admin.register(ExpertComment)
class ExpertCommentAdmin(admin.ModelAdmin):
    list_filter = ['expert', ]
`

models.py:
`python
class Expert(User):
    class Meta:
        proxy = True

class ExpertComment(models.Model):
    expert = models.ForeignKey(to='oauth.Expert', on_delete=models.CASCADE)
`

具体配置是这样的，但是admin后台界面上不会显示根据export字段进行搜索的下拉框。

**Comment by newpanjing** [comment]
OK，后续验证下，有这个问题下个版本进行修复。

**Comment by newpanjing** [comment]
![image](https://user-images.githubusercontent.com/13655483/81045857-ad0c2580-8ee9-11ea-8a57-f39707c56424.png)
我用你同样的代码，是可以显示的。
