### ISSUE TITLE
添加了文章类别以后页面挂掉了

### ISSUE THREAD

**Issue by Macile** [newpanjing/simpleui#187]
**bug描述**
简单的描述下遇到的bug：
添加文章类别后主页挂掉了，后台也删除不掉文章类别

**重现步骤**
1.添加文章类别

**环境**

1.操作系统：
2.python版本：3.6.5
3.django版本：2.0.7
4.simpleui版本：3.3

**其他描述**
![image](https://user-images.githubusercontent.com/26572845/69703344-25491080-112c-11ea-9f7c-ad72d7f88b08.png)

![image](https://user-images.githubusercontent.com/26572845/69703564-a0122b80-112c-11ea-8f72-caedbcfdcbed.png)

**Comment by newpanjing** [comment]
你自己url写的有问题，建议检查自己的代码。不是simpleui的bug。
