### ISSUE TITLE
是否可以脱离django，单独封装成前端模板？

### ISSUE THREAD

**Issue by alaxcc** [newpanjing/simpleui#188]
**你希望增加什么功能？**
1.是否可以脱离django，单独封装成前端模板？
2.
3.

**你希望哪些方面得到优化？**
1.
2.
3.

**留下你的联系方式，以便与你取得联系**
QQ：xxxxx
邮箱：roy@fentime.com

**Comment by newpepsi** [comment]
这种脱离django的解决方案已经有了。再做一遍没有啥意义

**Comment by alaxcc** [comment]
@newpepsi 哪有？我没看到lz这套全的

**Comment by newpanjing** [comment]
有考虑提取出html版本的，可以加群关注下：
# 群号:786576510
