### ISSUE TITLE
关于自定义用户模块后，新增、编辑用户页面比较乱的问题。

### ISSUE THREAD

**Issue by xojisi** [newpanjing/simpleui#190]
**bug描述**
简单的描述下遇到的bug：

当用户模块继承AbstractUser类(from django.contrib.auth.models import AbstractUser)时，
即自定义用户模块时，
新增用户（与编辑用户）的界面很混乱，如图所示。
https://s2.ax1x.com/2019/12/02/Qumgw6.png

**重现步骤**
<font color=red>建议使用simpleui_demo 测试，否则如果数据库有数据时，无法完成makemigrations操作。</font>
1.python manage.py startapp users
2.在users的models.py中加入
```python
from django.contrib.auth.models import AbstractUser
class UserProfile(AbstractUser):
    test = models.CharField(max_length=20,verbose_name=u'测试',default="test")
    class Meta:
        verbose_name = "测试"
        verbose_name_plural = verbose_name
```
4.setting.py加入，AUTH_USER_MODEL = 'users.UserProfile'
5.python manage.py makemigrations  （备注：因为之前用的是自带的用户模块，如果数据库有数据的话，会报错）
6.python manage.py migrate
7.打开后，如上图所示，用户信息的编辑，排序都是乱的。

**环境**

1.操作系统：
2.python版本：3.7
3.django版本：2.2.5
4.simpleui版本：3.5

**其他描述**

**Comment by newpanjing** [comment]
这是内置模块，具体请参考django文档。
