### ISSUE TITLE
simpleui貌似不支持django-guardian

### ISSUE THREAD

**Issue by loveward** [newpanjing/simpleui#195]
**你希望增加什么功能？**
1.针对object级鉴权方面的优化，比如django-guardian
2.对django3是否支持？
3.首页可以加上数据聚合的图表显示

**你希望哪些方面得到优化？**
1.在鉴权上是否可以设置二级密码，比如在setting中设置一个统一的写密码来对操作进行进一步授权考察，虽然本质上不能阻止，但是可以在形式上阻止。

**Comment by newpanjing** [comment]
问题1：simpleui只是django的皮肤，理论上django支持，simpleui就支持。
问题2：simpleui 下个版本3.7将会对django3 进行支持。今明两天内发布
问题3： 数据聚合图表属于业务层，需要自己实现。或者可以使用simplepro，支持图表。

其他的需要自己实现，不是框架做的事。
