### ISSUE TITLE
win10操作系统安装的时候，报字符编码错误

### ISSUE THREAD

**Issue by cncert** [newpanjing/simpleui#2]
我的环境是：win10操作系统，python3.6.4，django1.10.6
报错详细如下：
**$ pip install django-simpleui==1.4.3**
Collecting django-simpleui==1.4.3
  Using cached https://files.pythonhosted.org/packages/a1/64/9a031a3573e25ba51e3069ddd08f53b4b54846f952e18e6e09f5a03b49e7/django-simpleui-1.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\Users\wt\AppData\Local\Temp\pip-install-tmq8k1db\django-simpleui\setup.py", line 4, in <module>
        open('README.md', 'r').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa3 in position 112: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in D:\Users\wt\AppData\Local\Temp\pip-install-tmq8k1db\django-simpleui\

**Comment by newpanjing** [comment]
好的。明天我在win10系统上重现下该问题。

**Comment by cncert** [comment]
我觉得在setup.py中下边这个位置需要添加判断是python2还是python3：

如果是python2：
long_description = "\n".join([
    open('README.md', 'r').read(),
])

如果是python3：
long_description = "\n".join([
    open('README.md', 'r', encoding='utf-8').read(),
])

**Comment by newpanjing** [comment]
你用pip3 install django-admin 试试

**Comment by cncert** [comment]
ok，已解决，tks
