### ISSUE TITLE
布尔过滤项汉化

### ISSUE THREAD

**Issue by songguoxiong** [newpanjing/simpleui#200]
**你希望哪些方面得到优化？**
1. 布尔过滤项汉化

django原生admin：
![django](https://user-images.githubusercontent.com/33059503/70498075-3c3a2a80-1b50-11ea-8586-f8e6e6094d24.jpg)

simpleui admin：
![simpleui](https://user-images.githubusercontent.com/33059503/70498090-46f4bf80-1b50-11ea-8483-ae72903e1ccd.jpg)

**Comment by newpanjing** [comment]
simpleui支持国际化，所以汉化请自行编写代码实现。

**Comment by songguoxiong** [comment]
感觉并不是国际化的问题，在原生admin里已经是"汉化"的了，一切换到simpleui就变成布尔值了。
另外也尝试过在本地化的po文件中声明翻译如下，也都不生效。
```po
...
msgid "1"
msgstr "是"

msgid "True"
msgstr "是"

msgid "true"
msgstr "是"
...
```


现在感觉是个bug，看了下原生admin布尔过滤项的汉化位于
django.contrib.admin.filters.BooleanFieldListFilter类中的choices方法
```python
    def choices(self, changelist):
        for lookup, title in (
                (None, _('All')),# 这里汉化了
                ('1', _('Yes')),# 这里汉化了
                ('0', _('No'))):# 这里汉化了
        ...
```
是通过django.contrib.admin.templatetags.admin_list模块中的admin_list_filter调用的。可以通过断点确认调用。

但是切换到simpleui后，断点就不生效了，可见根本没有调用相关的方法。

**Comment by songguoxiong** [comment]
布尔值来自simpleui.templates.admin.search_form.html中的83、84行的label，是else分支默认值.
```html
<el-option label="True" value="True"></el-option>
<el-option label="False" value="False"></el-option>
```

**Comment by newpanjing** [comment]
好的，感谢反馈。在下个版本中进行优化。

发自我的iPhone
