### ISSUE TITLE
Exception Value:	 Reverse for 'blog_post_changelist' not found. 'blog_post_changelist' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by huajianzhanggithub** [newpanjing/simpleui#201]
**bug描述**
简单的描述下遇到的bug：

**重现步骤**
1.
2.
3.

**环境**

1.操作系统：
2.python3.8：
3.django3.0：
4.simpleui3.7：

**其他描述**
文章没法编辑!

**Comment by newpanjing** [comment]
贴下代码，url定义，admin定义，model定义，还有具体的错误堆栈。

**Comment by bmkyy** [comment]
> 贴下代码，url定义，admin定义，model定义，还有具体的错误堆栈。

我也遇到了同样的问题，原生代码ok，使用simpleui后无法进行分类、标签、文章的添加与修改，都是changlist出了问题，我将完整的原生代码发给您可以吗？https://github.com/bmkyy/typeidea

**Comment by newpanjing** [comment]
好的，有空我会验证下这个问题。

发自我的iPhone

**Comment by yswtrue** [comment]
应该是添加了自定义的url命名空间规则导致的
我之前定位是在提交表单时候的goBack这个函数生成的URL有点问题
