### ISSUE TITLE
宝塔面板部署后, simplepro报错, mobile is not defined

### ISSUE THREAD

**Issue by 1278651995** [newpanjing/simpleui#203]
**bug描述**
简单的描述下遇到的bug：
宝塔面板7.0.3, 使用python项目管理器, 选择uWsgi启动方式, python版本3.7.2, 关闭DEBUG, 进入admin管理页面后, 页面空白, F12出现
ReferenceError: mobile is not defined
    at wn.eval (eval at Ya (vue:6), <anonymous>:1:2187)
    at wn.e._render (vue:6)
    at wn.r (vue:6)
    at fn.get (vue:6)
    at new fn (vue:6)
    at vue:6
    at wn.$mount (vue:6)
    at wn.$mount (vue:6)
    at wn.t._init (vue:6)
    at new wn (vue:6)

**重现步骤**
1. 选择宝塔面板的python项目管理器
2. 选择Django-uWsgi启动, 关闭DEBUG模式
3. 进入admin, 登录后即可复现BUG

**环境**

1.操作系统：CentOS 7.3.1611
2.python版本：3.7.2
3.django版本：2.2.8
4.simpleui版本：3.2

**其他描述**
使用原生admin和simpleui无此问题

**Comment by newpanjing** [comment]
开启debug即可，原因自行查看Django文档。

发自我的iPhone

**Comment by 1278651995** [comment]
> 开启debug即可，原因自行查看Django文档。 发自我的iPhone
> […](#)
> 在 2019年12月18日，09:35，chensy ***@***.***> 写道： ﻿ bug描述 简单的描述下遇到的bug： 宝塔面板7.0.3, 使用python项目管理器, 选择uWsgi启动方式, python版本3.7.2, 关闭DEBUG, 进入admin管理页面后, 页面空白, F12出现 ReferenceError: mobile is not defined at wn.eval (eval at Ya (vue:6), :1:2187) at wn.e._render (vue:6) at wn.r (vue:6) at fn.get (vue:6) at new fn (vue:6) at vue:6 at wn.$mount (vue:6) at wn.$mount (vue:6) at wn.t._init (vue:6) at new wn (vue:6) 重现步骤 选择宝塔面板的python项目管理器 选择Django-uWsgi启动, 关闭DEBUG模式 进入admin, 登录后即可复现BUG 环境 1.操作系统：CentOS 7.3.1611 2.python版本：3.7.2 3.django版本：2.2.8 4.simpleui版本：3.2 其他描述 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

原生和simpleui都无此问题, 开启DEBUG也会出现这种情况, 也collectstatic了,

**Comment by newpanjing** [comment]
克隆后需要改变settings设置，或者搭配nginx。这是Django基础知识，不是simpleui bug。

发自我的iPhone

**Comment by 1278651995** [comment]
> 克隆后需要改变settings设置，或者搭配nginx。这是Django基础知识，不是simpleui bug。 发自我的iPhone
> […](#)
> 在 2019年12月18日，09:46，chensy ***@***.***> 写道： ﻿ 开启debug即可，原因自行查看Django文档。 发自我的iPhone … 在 2019年12月18日，09:35，chensy @.***> 写道： ﻿ bug描述 简单的描述下遇到的bug： 宝塔面板7.0.3, 使用python项目管理器, 选择uWsgi启动方式, python版本3.7.2, 关闭DEBUG, 进入admin管理页面后, 页面空白, F12出现 ReferenceError: mobile is not defined at wn.eval (eval at Ya (vue:6), :1:2187) at wn.e._render (vue:6) at wn.r (vue:6) at fn.get (vue:6) at new fn (vue:6) at vue:6 at wn.$mount (vue:6) at wn.$mount (vue:6) at wn.t._init (vue:6) at new wn (vue:6) 重现步骤 选择宝塔面板的python项目管理器 选择Django-uWsgi启动, 关闭DEBUG模式 进入admin, 登录后即可复现BUG 环境 1.操作系统：CentOS 7.3.1611 2.python版本：3.7.2 3.django版本：2.2.8 4.simpleui版本：3.2 其他描述 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 原生和simpleui都无此问题, 开启DEBUG也会出现这种情况, 也collectstatic了, — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢你的回答, 相关配置我已配置, 否则, simpleui也不会正确显示呀!

**Comment by 1278651995** [comment]
问题出现在原生和simpleui关闭DEBUG后都可以正常显示, 而simplepro无法正常显示!!!

**Comment by newpanjing** [comment]
把simpleui和simplepro升级至最新版，然后清除下浏览器缓存。
