### ISSUE TITLE
unpkg Rate exceeded

### ISSUE THREAD

**Issue by eshxcmhk** [newpanjing/simpleui#207]
**bug描述**
简单的描述下遇到的bug：
浏览器Console：
[Error] Failed to load resource: the server responded with a status of 429 () https://unpkg.com/element-ui/lib/index.js
[Error] Refused to execute https://unpkg.com/element-ui/lib/index.js as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.

单独打开链接：https://unpkg.com/element-ui/lib/index.js，响应Rate exceeded

**重现步骤**
1.打开登录页，无法加载输入框和登录按钮

**环境**

1.操作系统：MacOS 10.14.6
2.python版本：3.7.4
3.django版本：2.2.9
4.simpleui版本：3.8

**其他描述**

**Comment by linzh5410** [comment]
我也遇到了

**Comment by nishus266** [comment]
I am also facing the same issue Error 429

**Comment by abhinavsingh1995** [comment]
Same for me

**Comment by KotariAswini** [comment]
got same issues, any help....

**Comment by chuanhao01** [comment]
Adding a comment here as I am also facing the same issue

**Comment by Suntaz** [comment]
replace with https://cdnjs.cloudflare.com/ajax/libs/element-ui/2.13.0/index.js

**Comment by fahidmohammad** [comment]
any alternative for css?

**Comment by Atrony** [comment]
same issue for our website, that relies on unpkg.com cdn.

**Comment by xcmbxcmb** [comment]
Same for us

**Comment by neuliyiping** [comment]
unpkg被墙？？

**Comment by Sen-Gupta** [comment]
Same here? The files are not being served any more.

**Comment by nishus266** [comment]
Yes I replaced all my unpkg cdn to local js and css file by download it from it's official websites.

**Comment by neuliyiping** [comment]
源码更换引用文件，亲测可行

**Comment by abhinavsingh1995** [comment]
Its working now

**Comment by frozenzj** [comment]
first step:
cmd run:
`
python manage.py collectstatic
`
second step:
edit settings.py file:
add below setting
`
SIMPLEUI_STATIC_OFFLINE=True
`

**Comment by eshxcmhk** [comment]
> first step:
> cmd run:
> `python manage.py collectstatic`
> second step:
> edit settings.py file:
> add below setting
> `SIMPLEUI_STATIC_OFFLINE=True`

完美解决！！！加载慢的问题已没了

**Comment by newpanjing** [comment]
> > 第一步：
> > cmd运行：
> > `python manage.py collectstatic`
> > 第二步：
> > 编辑settings.py文件：
> > 添加以下设置
> > `SIMPLEUI_STATIC_OFFLINE=True`
> 
> 完美解决！！！加载慢的问题已没了


Great! Third party CDN out of the problem, we recommend the use of local load!
