### ISSUE TITLE
关于功能优化的建议

### ISSUE THREAD

**Issue by xojisi** [newpanjing/simpleui#208]
**你希望增加什么功能？**
1. 导出的数据以前端页面展示的数据为准。
比如在数据库里存的是：
Table name:  Teacher
```
ID    school   name    status 
1      2       张三        0
```

在前端页面显示的是
表名：老师
```
ID    学校     姓名    状态   管理学生（备注1）
1     北大    张三      △        35人
```

备注1：该字段由admin中的list_play 与 model中加了自定义函数产生，数据不在数据库中

需求：
用django-import-export导出的数据，数据库是什么，那导出就是什么
如果simpleUI集成django-import-export后，希望做到的是，前端页面现实的是什么，那么导出的是什么。

**Comment by xojisi** [comment]
另,xadmin是有这个功能的

**Comment by newpanjing** [comment]
该建议请异步至`django-import-export`处提，simpleui只是皮肤不包含任何业务逻辑处理。谢谢。
