### ISSUE TITLE
找到另一个文件，其目标路径为“ dist / js / marked.min.js”。 由于仅收集第一个遇到的文件，因此它将被忽略。 如果这不是您想要的，请确保每个静态文件都有唯一的路径。

### ISSUE THREAD

**Issue by dba-ws** [newpanjing/simpleui#209]
**bug描述**
python3 manage.py collectstatic
报错
Found another file with the destination path 'dist/js/marked.min.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

**Comment by newpanjing** [comment]
simpleui并不包含此文件。
