### ISSUE TITLE
数据需要分页请求

### ISSUE THREAD

**Issue by liaogx** [newpanjing/simpleui#216]
前端分页显示有两种实现方法：
1. 数据从后端一次全部获取，然后分页显示
2. 数据分页获取，点击下一页发送一次ajax get请求，然后显示
![前端分页显示效果](https://user-images.githubusercontent.com/49523956/71649814-a52a5200-2d4c-11ea-8208-2c9e7d3a544b.png)
目前最新版的simpleui使用了第一种方式，数据表稍大一点的时候浏览器就会卡死

**Comment by bijack** [comment]
+1，数据量一大加载太慢，确实很影响用户体验。

**Comment by WalkerWang731** [comment]
这个分页是django原生的分页模式，建议启用一下 django-debug-toolbar 观察一下看看哪里影响的速度。我试过simpleui 打开150W+的表，速度可以控制在2秒内全部展现。目前我所知道的admin.py中 “date_hierarchy” 这个参数在大表中影响性能是致命的，不知道你那边admin.py的配置是怎么配的。

**Comment by ihewro** [comment]
4000+数据在本地加载都需要5～6 s左右
