### ISSUE TITLE
源码安装登录页面报错

### ISSUE THREAD

**Issue by izqutcom** [newpanjing/simpleui#221]
源码安装配置默认后台模板为simpleui后admin登录页面报错。

`TemplateSyntaxError at /admin/`
`'simpletags' is not a registered tag library. Must be one of:`
`admin_list`
`admin_modify`
`admin_urls`
`cache`
`i18n`
`l10n`
`log`
`static`
`tz`

Django 版本 3.0.1
Django-Simpleui 版本：3.9

**Comment by izqutcom** [comment]
已解决。

**Comment by NaNShaner** [comment]
> 已解决。

同样的问题，求教一下如何解决的？
