### ISSUE TITLE
谷歌统计等功能

### ISSUE THREAD

**Issue by 373005226** [newpanjing/simpleui#224]
**你希望增加什么功能？**
** what features do you wish to add? * *
1.类似谷歌分析功能，比如当天的访客量，销售统计等
2.
3.

**你希望哪些方面得到优化？**
1.每次点击图片的时候都会直接占满整个框，要关掉标签页重新打开才能恢复正常
2.
3.

**留下你的联系方式，以便与你取得联系**
** what would you like to see optimized? * *
QQ：373005226
E-mail：373005226@qq.com

**Comment by newpanjing** [comment]
可以自行参考django文档，继承页面添加block实现。simpleui已经预留了block可以自行扩展。
