### ISSUE TITLE
前端js报错 TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by hardyxia2018** [newpanjing/simpleui#227]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:
前端js报错 TypeError: Cannot read property 'style' of null
后端：
Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\django\template\base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'home'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [home] in "[{'True': True, 'False': False, 'None': None}, 
**重现步骤**
** repeat step **
1.
2.
3.

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....
Windows
2.Python Version：
3.6.7
3.Django Version：
1.11.11
4.SimpleUI Version：
django-simpleui-3.9

**Description**
![image](https://user-images.githubusercontent.com/44759712/73426232-c0e63f80-436e-11ea-940c-886c2fe76a22.png)
![image](https://user-images.githubusercontent.com/44759712/73426358-0acf2580-436f-11ea-9c18-8d9970b4cdd1.png)

**Comment by newpanjing** [comment]
发一下settings的配置

**Comment by Abraverman666** [comment]
建议django版本换成2.2   ，或者simpleui换成2.5版本
