### ISSUE TITLE
无法查看内嵌frame

### ISSUE THREAD

**Issue by cxgreat2014** [newpanjing/simpleui#228]
django版本：3.0.3

错误：
![image](https://user-images.githubusercontent.com/15062548/75646290-1e2e2300-5c84-11ea-9a41-9fff6dc39e75.png)

错误位置：
![image](https://user-images.githubusercontent.com/15062548/75646206-d0191f80-5c83-11ea-9479-05249e571042.png)
实际上middleware设置：
![image](https://user-images.githubusercontent.com/15062548/75646234-ecb55780-5c83-11ea-9dfb-eb396f326440.png)
可知，django把middleware设置给强转tuple了。

解决方案：让用户自行添加middleware
![image](https://user-images.githubusercontent.com/15062548/75646328-3e5de200-5c84-11ea-9cbc-9a0b5537b5d0.png)

另外吐槽一下，middlewares能不能改成middleware，拼写不规范，

**Comment by newpanjing** [comment]
已经在simpleui4.0中修复这个问题

**Comment by cxgreat2014** [comment]
升级之后问题依然存在，烦请重新打开此问题。
![image](https://user-images.githubusercontent.com/15062548/84993916-7e39ce00-b17c-11ea-8184-c4cbd54c48d5.png)

![image](https://user-images.githubusercontent.com/15062548/84993863-69f5d100-b17c-11ea-8dc4-d262c3c78434.png)
