### ISSUE TITLE
使用simpleui后手机端打开页面问题。

### ISSUE THREAD

**Issue by lx37506** [newpanjing/simpleui#233]
**bug描述**
* *Bug description * * 
1、手机端打开页面只能显示一屏幕，上下左右均不可滑动。使用电脑chrome浏览器模拟手机端没问题。手机型号Iphone6/7
2、双击快速切换标签跳转会出现错误，重新刷新页面也不行。

简单的描述下遇到的bug：
Briefly describe the bugs encountered:

**重现步骤**
** repeat step **
1.
2.
3.

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....
Ubuntu18.04
2.Python Version：
3.6.5
3.Django Version：
2.2.11
4.SimpleUI Version：
3.9.1

**Description**

**Comment by newpanjing** [comment]
可以升级到最新版的`simpleui`试试，我这边使用iPhone12内置的Safari浏览器测试一切皆正常。
