### ISSUE TITLE
动态控制表格列的显示与隐藏 

### ISSUE THREAD

**Issue by gm8300130** [newpanjing/simpleui#238]
**你希望增加什么功能？**
** what features do you wish to add? * *
1. 动态控制表格列的显示与隐藏 

**你希望哪些方面得到优化？**
1. 动态控制表格列的显示与隐藏 

请问动态控制表格列的显示与隐藏
我看pro有这功能
请问simpleui版会实装吗？

还是有教学可以自己设定？ 谢谢

**Comment by newpanjing** [comment]
simpleui目前是jQuery的动态表格，如果要实现动态显示和隐藏，需要自己来实现。目前simpleui中不考虑引入这个功能，实现有一定难度。
