### ISSUE TITLE
静态资源建议从 unpkg 改为 jsDelivr

### ISSUE THREAD

**Issue by zmaplex** [newpanjing/simpleui#239]
**你希望哪些方面得到优化？**
1. 静态资源建议从 unpkg 改为 jsDelivr

原因

- unpkg 资源托管在 Cloudflare 上，中国大陆访问不理想。
- jsDelivr在中国大陆有CDN节点，海外则托管在 CloudFlare 上。
- 从这两点来看，个人建议把静态资源修改成 jsDelivr 的 。

测速地址

- https://unpkg.com/jquery@3.4.1/dist/jquery.min.js
  - 加载速度为：229 ms
- https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js 
  - 加载速度为：57 ms

**Comment by newpanjing** [comment]
感谢建议 下个版本调整为可配置的

发自我的iPhone

**Comment by yinzhuoqun** [comment]
> **你希望哪些方面得到优化？**
> 
> 1. 静态资源建议从 unpkg 改为 jsDelivr
> 
> 原因
> 
> * unpkg 资源托管在 Cloudflare 上，中国大陆访问不理想。
> * jsDelivr在中国大陆有CDN节点，海外则托管在 CloudFlare 上。
> * 从这两点来看，个人建议把静态资源修改成 jsDelivr 的 。
> 
> 测速地址
> 
> * https://unpkg.com/jquery@3.4.1/dist/jquery.min.js
>   
>   * 加载速度为：229 ms
> * https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
>   
>   * 加载速度为：57 ms
我自己直接改成  bootcdn 了，反正国内用。

**Comment by ading2016** [comment]
请问在哪个地方可以把unpkg.com 的链接替换成jsDelivr的

**Comment by yinzhuoqun** [comment]
> 请问在哪个地方可以把unpkg.com 的链接替换成jsDelivr的

标题：Django simpleUI 修改 element-UI 引用的 index.js 和 index.css 链接 以及 base.html 的 vue 资源链接
链接：https://xieboke.net/article/260/

**Comment by ading2016** [comment]
> > 请问在哪个地方可以把unpkg.com 的链接替换成jsDelivr的
> 
> 标题：Django simpleUI 修改 element-UI 引用的 index.js 和 index.css 链接 以及 base.html 的 vue 资源链接
> 链接：https://xieboke.net/article/260/

可以了，非常感谢！

**Comment by newpanjing** [comment]
已经在simpleui 4.0版本中修复这个问题
