### ISSUE TITLE
快捷链接的bug

### ISSUE THREAD

**Issue by wd-chris** [newpanjing/simpleui#240]
**bug描述**
在通过快捷链接打开页面后，这个时候点击首页页签，再点回刚刚打开的页签，页签内容变成首页内容

**重现步骤**
1.先点击快捷链接第一个，打开页面
2.点击首页页签
3.切换回刚打开的页签

https://www.88cto.com/admin/#/
http://simplepro.demo.88cto.com/#/
demo页面也能复现

**Comment by newpanjing** [comment]
这个问题暂时没有复现出来
