### ISSUE TITLE
字段过多时，显示字段的选项显示不全

### ISSUE THREAD

**Issue by xojisi** [newpanjing/simpleui#241]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:
图片：https://s1.ax1x.com/2020/03/27/GPUjqs.jpg
如图所示，字段过多时，右边显示字段的选项显示不全。

**重现步骤**
** repeat step **
1.
2.
3.

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....

2.Python Version：

3.Django Version：

4.SimpleUI Version：

**Description**

**Comment by newpanjing** [comment]
后续版本增加滚动条解决此问题

发自我的iPhone

**Comment by newpanjing** [comment]
已经在1.4中修复该问题
