### ISSUE TITLE
将simplepro首页的图表显示作为在setting配置的常量。

### ISSUE THREAD

**Issue by xojisi** [newpanjing/simpleui#242]
**你希望增加什么功能？**
** what features do you wish to add? * *
1. 
2. 
3.

**你希望哪些方面得到优化？**
1. 将simplepro首页的图表显示作为在setting配置的常量。（毕竟有时候不需要的话，又不配置，看起来比较奇怪），虽然可以在html模板里删除，但是能放在settings.py里配置成常量的话，体验会更好。
2.基于上述，图标的显示可考虑接入用户组或权限的配置，即不同的人能看到不同的图表。
3.

**留下你的联系方式，以便与你取得联系**
** what would you like to see optimized? * *
QQ：
E-mail：271398289@qq.com

**Comment by newpanjing** [comment]
在新版1.4中已经增加了该项配置：

## 显示隐藏首页默认图表

|参数|说明|
|---|---|
|SIMPLEPRO_CHART_DISPLAY|配置Simple Pro是否显示首页的图标，默认为True，显示图表，False不显示|

```python
# 配置Simple Pro是否显示首页的图标，默认为True，显示图表，False不显示
SIMPLEPRO_CHART_DISPLAY = True
```
