### ISSUE TITLE
simplePro时间筛选问题

### ISSUE THREAD

**Issue by xojisi** [newpanjing/simpleui#243]
**你希望增加什么功能？**
** what features do you wish to add? * *
django admin，自带的筛选功能代码编写如下：
```
models.py:
date = models.DateField(default=timezone.now, verbose_name=u"日期")
```
```
admin.py    
list_filter = ( 'date',)
```
筛选结果如图所示，
第一张我筛选2月28日-2月28日，结果出来3月31日？
第二张我筛选3月30日-3月30日，结果出来3月31日？
https://s1.ax1x.com/2020/03/31/GM7HgO.jpg
https://s1.ax1x.com/2020/03/31/GM7J9f.jpg

然后我去掉simplepro后，使用原版admin试了一下。判断，这个属于自带其实筛选本身的功能缺陷。
https://s1.ax1x.com/2020/03/31/GM763T.png

建议：
simplepro兼容插件django-daterange-filter，以便更好的使用日期筛选
介绍参考：https://blog.csdn.net/ZeroChia/article/details/82458420
下图为使用插件后的筛选。筛选结果没有出错。
https://s1.ax1x.com/2020/03/31/GM4a24.jpg

**你希望哪些方面得到优化？**
1.
2.
3.

**留下你的联系方式，以便与你取得联系**
** what would you like to see optimized? * *
QQ：xxxxx
E-mail：271398289@qq.com

**Comment by newpanjing** [comment]
在新版1.4中已经修复该问题。
