### ISSUE TITLE
SIMPLE日期筛选的问题

### ISSUE THREAD

**Issue by xojisi** [newpanjing/simpleui#244]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:
使用models.DateField时，list_filter筛选的结果是不准的
第一张我筛选2月28日-2月28日，结果出来3月31日？
第二张我筛选3月30日-3月30日，结果出来3月31日？
https://s1.ax1x.com/2020/03/31/GM7HgO.jpg
https://s1.ax1x.com/2020/03/31/GM7J9f.jpg

而使用models.DateTimeField时，list_filter筛选的结果是准的
准的就不放图了。虽然搜索当天时要加时间段比较麻烦
**重现步骤**
** repeat step **
1.
2.
3.

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....

2.Python Version：

3.Django Version：

4.SimpleUI Version：

**Description**

**Comment by newpanjing** [comment]
在新版1.4中已经修复该问题。
