### ISSUE TITLE
error occurs in list_filter

### ISSUE THREAD

**Issue by limebear** [newpanjing/simpleui#249]
If pk_id is more than 4 digits, an error occurs in list_filter.

item is exposed normally, but If you select and search for the problem value, 

it is redirected to the main page.

It seems to be solved by processing 'to_str' in option.0 of search_form.html

1.Operating System：
(Windows/Linux/MacOS)....

2.Python Version：

3.Django Version：2.2.4

4.SimpleUI Version：3.9

**Comment by newpanjing** [comment]
Thanks for your feedback. The problem will be fixed in the near future.

**Comment by newpanjing** [comment]
Can you send your code to have a look? What kind of pk is it?
