### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by yinzhuoqun** [newpanjing/simpleui#251]
#### simple UI 版本：
3.9.1

#### 复现步骤：
登录到后台主页

#### 浏览器 F12 控制台错误日志：
index.js?_=3.9.1:98 Uncaught TypeError: Cannot read property 'replace' of undefined
    at window.simple_call (index.js?_=3.9.1:98)
    at latest?callback=simple_call:1

#### 出错位置代码片段：
    window.simple_call = function (data) {

        var o = __simpleui_version.replace(/\./g, '');
        var n = data.data.name.replace(/\./g, '');
        while(o.length!=3){
            o += '0';
        }
        while(n.length!=3){
            n += '0';
        }
        var oldVersion = parseInt(o)
        var newVersion = parseInt(n)
        var body = data.data.body;
        if (oldVersion < newVersion) {
            app.upgrade.isUpdate = true;
            app.upgrade.body = body;
            app.upgrade.version = data.data.name;

        }
    }

#### 请求链接：
[https://api.github.com/repos/newpanjing/simpleui/releases/latest?callback=simple_call](https://api.github.com/repos/newpanjing/simpleui/releases/latest?callback=simple_call)

#### 出错原因：
返回数据缺少对应的字段

**Comment by newpanjing** [comment]
感谢反馈，github接口有变更，近期将做更新。
