### ISSUE TITLE
simplePRO 注销时，无法操作

### ISSUE THREAD

**Issue by xojisi** [newpanjing/simpleui#256]
[![YZJU0K.png](https://s1.ax1x.com/2020/05/07/YZJU0K.png)](https://imgchr.com/i/YZJU0K)
图片挂了点这里：https://s1.ax1x.com/2020/05/07/YZJU0K.png
描述：
当手机屏幕过小时，如Galaxy S5 360*640 （谷歌浏览器自带），实际现在还是有很多小屏的手机。
点击了“注销”，弹出的提示框，无法点击“是” ，只能点击“否”

**Comment by xojisi** [comment]
iphone 5/SE 也存在这个问题

**Comment by newpanjing** [comment]
下个版本适配下

发自我的iPhone
