### ISSUE TITLE
希望可以加载一个菜单生成器。

### ISSUE THREAD

**Issue by Chise1** [newpanjing/simpleui#268]
**你希望增加什么功能？**
** what features do you wish to add? * *
1.动态加载菜单和路由的时候，可以通过加载函数的方式，传入登录客户的user，做到自定义权限控制数据表。而不是只能加载一个dict。

**留下你的联系方式，以便与你取得联系**
** what would you like to see optimized? * *
QQ：531189371
E-mail：chise123@live.com

**Comment by newpanjing** [comment]
这个可以自己稍微扩展下，需求不多，暂时不考虑。如果你扩展好了，也可以合并到dev分支中来。
