### ISSUE TITLE
新增用户时，有很多英文没翻译过来。

### ISSUE THREAD

**Issue by xojisi** [newpanjing/simpleui#269]
simpleUI 4.0
django 3.0.5
python 3.8

![微信截图_20200604093143](https://user-images.githubusercontent.com/28687402/83705119-9a9b1e00-a646-11ea-8bcc-a659a8cf69e3.png)
图片挂了看这里：https://ftp.bmp.ovh/imgs/2020/06/d861eecddaca267b.jpg
新增用户时，有很多英文没翻译过来。

**Comment by newpanjing** [comment]
Django官方未翻译，等Django后续版本更新即可。
