### ISSUE TITLE
第一个标签页打开报错。

### ISSUE THREAD

**Issue by xojisi** [newpanjing/simpleui#270]
环境：
simpleUI 4.0
django 3.0.5
python 3.8

![1](https://user-images.githubusercontent.com/28687402/83705967-e222a980-a648-11ea-8165-8d01cf649f6c.jpg)

图片挂了看这里：https://ftp.bmp.ovh/imgs/2020/06/0d010807991ca37d.jpg

问题描述：
SIMPLEUI SIMPLEPRO 都存在这个问题
。
1.打开导航最左边第一个菜单
2.然后再打开任意一个菜单。
3.在切换回第一个菜单，都会出现页面错乱，或是报错的情况。

**Comment by xojisi** [comment]
这个情况，在simpleUI 演示，以及simplePro演示里，均有这个情况。
情况：
1.打开导航最左边第一个菜单
2.然后再打开任意一个菜单。
3.在切换回第一个菜单，都会出现页面错乱，或是报错的情况

**Comment by newpanjing** [comment]
最新版已经修复，演示环境还没有更新而已。

发自我的iPhone
