### ISSUE TITLE
定制admin site，登录后台后无法新增和修改

### ISSUE THREAD

**Issue by liuchangfu** [newpanjing/simpleui#271]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:

定制admin site，登录后台后无法新增和修改

**重现步骤**
** repeat step **
1.
2.
3.

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....

2.Python Version：3.8

3.Django Version： 3.0.4 

4.SimpleUI Version： 4.0.2

**Description**

在admin定制site_header， site_title，index_title 后，在url添加新的admin后台路由地址后，登录后台后，app无法新增和编辑

报错信息如下：
![image](https://user-images.githubusercontent.com/23349356/84216782-1987cf00-aafd-11ea-8bb4-364d3f7f68ca.png)

![image](https://user-images.githubusercontent.com/23349356/84216812-2e646280-aafd-11ea-9841-36a535a0ab9f.png)

**Comment by newpanjing** [comment]
重启项目
