### ISSUE TITLE
Can't use simpleui 4.0.2 with django 3.0.7

### ISSUE THREAD

**Issue by cxgreat2014** [newpanjing/simpleui#272]
#228 not fix!!!
![image](https://user-images.githubusercontent.com/15062548/85122465-2e7d0480-b259-11ea-9417-76dcbf5ce6bc.png)
![image](https://user-images.githubusercontent.com/15062548/85122472-32108b80-b259-11ea-9dd8-5ddaf342f353.png)

**Comment by newpanjing** [comment]
从settings.py中 移除`django.middleware.clickjacking.XFrameOptionsMiddleware`该中间件即可。
