### ISSUE TITLE
menu顺序会导致部分页面打开空白

### ISSUE THREAD

**Issue by fanmlei** [newpanjing/simpleui#277]
**bug描述**
* *Bug description * * 

页面空白

简单的描述下遇到的bug：
Briefly describe the bugs encountered:

项目部分结构如下
```
device_app:
     - models:
        - Device
        - DeviceCategory
     - admin
        - DeviceAdmin
        - DeviceCategoryAdmin

settings:
    SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menus': [{
        'name': '设备管理',
        'icon': 'fa fa-list',
        'app': 'device',
        'models': [{
            'name': '设备类别',
            'icon': 'fa fa-tags',
            'url': 'device/devicecategory/'
        }, {
            'name': '设备管理',
            'icon': 'fa fa-database',
            'url': 'device/device/'
        }]
    }]
}
```
**重现步骤**
** repeat step **
1. 访问 http://127.0.0.1:8000/admin/#device/device/  页面正常
![image](https://user-images.githubusercontent.com/19201217/85883118-1128d700-b813-11ea-803a-c192fab865af.png)

2. 访问 http://127.0.0.1:8000/admin/#device/devicecategory/  空白显示
![image](https://user-images.githubusercontent.com/19201217/85883302-59e09000-b813-11ea-878f-d05c7fcbaf05.png)

3. 访问 http://127.0.0.1:8000/admin/device/devicecategory/ 可显示出页面，但是没有侧边栏等，只有主体部分
![image](https://user-images.githubusercontent.com/19201217/85882874-a4154180-b812-11ea-97e9-bc247d1950a4.png)

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....
MacOS

2.Python Version：
Python3.7
3.Django Version：
django: 2.2.7
4.SimpleUI Version：
django-simpleui : 4.0.2

**Description**
情况如上所说，具体原因推测是前端路由匹配顺序的问题，调整models顺序可以正常显示，这个点可以是不是可以在vue的router里面避免（很久没有写vue了有些忘记了，不清楚是否可行），或者在文档里面说明一下。
还有部分字体无法显示，例如`fa fa-line-chart`
![image](https://user-images.githubusercontent.com/19201217/85884108-a8425e80-b814-11ea-9593-c82c8c6afa78.png)
![image](https://user-images.githubusercontent.com/19201217/85884158-c3ad6980-b814-11ea-886a-c75b0f388243.png)

**Comment by newpanjing** [comment]
提交bug到 django issue
