### ISSUE TITLE
assert info_dir, "%s .dist-info directory not found" % req

### ISSUE THREAD

**Issue by tuhaolam** [newpanjing/simpleui#278]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:
```
  File "/home/user/.local/share/virtualenvs/aps-ERrBfxQB/lib/python3.6/site-packages/pip/_internal/wheel.py", line 465, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: simpleui .dist-info directory not found
```
**重现步骤**
** repeat step **
1.
2.
3.

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....

2.Python Version：
py3.6.8
3.Django Version：
django 2.2.3
4.SimpleUI Version：
4.0.3

**Description**

**Comment by tuhaolam** [comment]
补充：尽管报错，但不影响使用。

**Comment by newpanjing** [comment]
可以使用pip安装。
