### ISSUE TITLE
发现两个BUG

### ISSUE THREAD

**Issue by ShiningSYK** [newpanjing/simpleui#28]
第一个BUG是针对表单的显示，当无数据时，原始django显示提示增加数据，但是simpleui显示model注册时定义显示的表头，如图
![image](https://user-images.githubusercontent.com/45619625/57354979-911f5800-719f-11e9-949a-991cfc6397f6.png)

第二个BUG是，本人初入Django坑，对admin显示的菜单控制不太清楚，在用simpleui设置自定义菜单时发现系统默认菜单也在，即使我设置了system_keep=False（按照官方说法，这个应该是显示/关闭系统菜单的开关）也没用，但后来我发现把menus中这个配置删掉，也就是不要写system_keep，就可以关闭系统默认菜单了
删除前效果如图：
![image](https://user-images.githubusercontent.com/45619625/57355301-4b16c400-71a0-11e9-8dde-f937957548ca.png)

删除后效果如图：
![image](https://user-images.githubusercontent.com/45619625/57355317-5538c280-71a0-11e9-9b6b-6193c7f7bbe1.png)

**Comment by newpanjing** [comment]
第一个bug 是用的什么浏览器？和操作系统？

**Comment by ShiningSYK** [comment]
> 第一个bug 是用的什么浏览器？和操作系统？

win10+Edge/Chorme 都不可以

**Comment by ShiningSYK** [comment]
> 第一个bug 是用的什么浏览器？和操作系统？

win10 + Edge
Chrome是可以的
