### ISSUE TITLE
增加关闭菜单图标的可选项

### ISSUE THREAD

**Issue by zmaplex** [newpanjing/simpleui#281]
**你希望增加什么功能？**

增加关闭菜单图标的可选项

```python
SIMPLEUI_ENABLE_ICON = False
```
刚开始一个项目的时候，有大概十几个菜单项，有的图标使用的是默认图片，看着很难受。

期望增加一个关闭显示图标的功能。

**你希望哪些方面得到优化？**
1. 增加关闭菜单图标的可选项
2.
3.

**留下你的联系方式，以便与你取得联系**
** what would you like to see optimized? * *
QQ：xxxxx
E-mail：xxx@xxx.com

**Comment by newpanjing** [comment]
https://simpleui.88cto.com/docs/simpleui/QUICK.html#%E9%BB%98%E8%AE%A4%E5%9B%BE%E6%A0%87
