### ISSUE TITLE
登录的时候页面无法调整，一直转圈圈

### ISSUE THREAD

**Issue by linorwang** [newpanjing/simpleui#286]
**bug描述**
* *Bug description * * 
使用simpleui，登录超级后台一直转圈圈，无法跳转,刷新一下就可以登录页面

简单的描述下遇到的bug：
Briefly describe the bugs encountered:

**重现步骤**
** repeat step **
1.
2.
3.

**环境**
** environment**
win7 64位 谷歌浏览器版本 83.0.4103.116（正式版本） （64 位）

1.Operating System：
(Windows/Linux/MacOS)....

2.Python Version：
python3.8.3
3.Django Version：
django3.0.7
4.SimpleUI Version：
simple4.0,3

**Description**
![image](https://user-images.githubusercontent.com/23013733/87391604-a0890500-c5dd-11ea-8370-1387d0f9374f.png)

**Comment by bimo12138** [comment]
请问控制台显示的是什么呢？或者network里面的是什么情况呢？
还是后端有报错信息，麻烦截图展示一下

**Comment by newpanjing** [comment]
使用离线模式
