### ISSUE TITLE
tabular inline DateTime field overlap

### ISSUE THREAD

**Issue by clashthe** [newpanjing/simpleui#288]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:
![image](https://user-images.githubusercontent.com/21126254/87821984-5042c900-c8a3-11ea-9865-ec97103dbbf0.png)

**重现步骤**
** repeat step **
1.
2.
3.

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....
wsl deb10
2.Python Version：
3.7
3.Django Version：
3.0.8
4.SimpleUI Version：
latest

**Description**

**Comment by bimo12138** [comment]
能不能将这个部分的model 和 admin 部分的代码展示一下呢？

**Comment by clashthe** [comment]
class UserModel1(admin.TabularInline):
    model = Model1

    def get_queryset(self, request):
        qs = super().get_queryset(request)
        return qs.select_related('user', )

@admin.register(get_user_model())
class MyUserAdmin(UserAdmin):
    inlines = (UserProfile, UserModel1)

############
class Model1(models.Model):
    class Meta:
        ordering = ['-time_created']

    time_created = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(get_user_model(), on_delete=models.SET(get_deleted), null=True, )

**Comment by bimo12138** [comment]
![image](https://user-images.githubusercontent.com/36919327/87845823-99c00200-c8fd-11ea-827c-16120d2f3a5a.png)
![image](https://user-images.githubusercontent.com/36919327/87845826-a0e71000-c8fd-11ea-8d4d-851b370ba783.png)
![image](https://user-images.githubusercontent.com/36919327/87845829-a6445a80-c8fd-11ea-8fe4-808c4c923e54.png)
不好意思，我这复现不出来，请问能够加qq群进行交流吗？方便问题的定位

**Comment by clashthe** [comment]
在model field 很多 右侧溢出时会出现
class Model1(models.Model):
    class Meta:
        ordering = ['-time_created']

    time_created = models.DateTimeField(default=timezone.now)
    time_created = models.DateTimeField(default=timezone.now)
    time_created = models.DateTimeField(default=timezone.now)
    time_created = models.DateTimeField(default=timezone.now)
    time_created = models.DateTimeField(default=timezone.now)
    time_created = models.DateTimeField(default=timezone.now)
    time_created = models.DateTimeField(default=timezone.now)
    time_created = models.DateTimeField(default=timezone.now)
    time_created = models.DateTimeField(default=timezone.now)
    time_created = models.DateTimeField(default=timezone.now)
    time_created = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(get_user_model(), on_delete=models.SET(get_deleted), null=True, )

    def __str__(self):
         return f'''{str(self.user)} {str(self.time_created)} '''

**Comment by clashthe** [comment]
有tg群吗

**Comment by clashthe** [comment]
![image](https://user-images.githubusercontent.com/21126254/87846135-181da380-c900-11ea-9302-50259f059f49.png)

**Comment by bimo12138** [comment]
没有呢！只有qq和微信

**Comment by clashthe** [comment]
![image](https://user-images.githubusercontent.com/21126254/87846187-a003ad80-c900-11ea-8884-6e86706f4280.png)
不溢出时

**Comment by bimo12138** [comment]
请问你这是用的内联表单展示的吗？

**Comment by clashthe** [comment]
不了解中文术语 你说的是inline?
from django.contrib.auth.admin import UserAdmin
class MyUserAdmin(UserAdmin):
    inlines = (UserProfile, UserModel1)

**Comment by bimo12138** [comment]
是的
![image](https://user-images.githubusercontent.com/36919327/87846525-202b1280-c903-11ea-8621-116b6b3443b4.png)
![image](https://user-images.githubusercontent.com/36919327/87846530-24efc680-c903-11ea-9bf4-fa889e327060.png)
但是css错误还是存在的，我马上想办法修改

**Comment by clashthe** [comment]
datetime field 要排在第一个

**Comment by bimo12138** [comment]
![image](https://user-images.githubusercontent.com/36919327/87846670-2f5e9000-c904-11ea-96a9-e387d3335d04.png)
这个错误是没问题的，但是才开始的那个bug复现不了

**Comment by clashthe** [comment]
哪个bug

**Comment by bimo12138** [comment]
![image](https://user-images.githubusercontent.com/36919327/87846741-b27fe600-c904-11ea-9558-e93e04f0f7ff.png)
这个啊

**Comment by bimo12138** [comment]
兄弟，手机端的兼容不咋好做，实测 宽度低于550px 会出现表格内容展示问题

**Comment by hidaen** [comment]
DateTimeField 有没有好点的UI，现在这个自带的太别扭了
