### ISSUE TITLE
[bug] django-import-export兼容性问题

### ISSUE THREAD

**Issue by hackerliang** [newpanjing/simpleui#29]
**bug描述**
简单的描述下遇到的bug：
![图片](https://user-images.githubusercontent.com/32356999/57098891-ba7a5700-6d4d-11e9-9754-9fd1629c8696.png)
两种写法，第二种写法无法select export format
![图片](https://user-images.githubusercontent.com/32356999/57098994-f3b2c700-6d4d-11e9-9663-7e6b5e152c7f.png)

**重现步骤**
1.
2.
3.

**环境**

1.操作系统：windows10 home 1803
2.python版本：python3.7.3 and python 3.6.0
3.django版本：django 2.1.8 and 2.2.1
4.simpleui版本：2.0.6 and 2.1b0

**其他描述**

**Comment by newpanjing** [comment]
近期修复

**Comment by newpanjing** [comment]
2.1 已经修复这个bug了。月底之前发布正式版

![image](https://user-images.githubusercontent.com/13655483/58001117-29f19400-7b0d-11e9-9a8b-c1295ee84806.png)

**Comment by newpanjing** [comment]
已经修复该bug，请升级到2.1。
```shell
pip install django-simpleui --upgrade
```
