### ISSUE TITLE
import_export定制formats，继承ExportActionModelAdmin时，不能正常导出文件，提示未选择动作

### ISSUE THREAD

**Issue by lnysky** [newpanjing/simpleui#293]
**bug描述**
* *Bug description * * 
import_export定制formats，继承ExportActionModelAdmin时，不能正常导出文件，提示未选择动作

简单的描述下遇到的bug：
Briefly describe the bugs encountered:
不能正常导出文件，提示未选择动作，且格式下拉显示的不是定制的格式，而是全部格式

**重现步骤**
** repeat step **

@admin.register(Test)
class TestAdmin(ExportActionModelAdmin):
    formats = [XLS, XLSX]
    resource_class = TestResource

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....
windows

2.Python Version：
3.6

3.Django Version：
2.2

4.SimpleUI Version：
4.0.3

**Description**

**Comment by newpanjing** [comment]
需要勾选数据

发自我的iPhone

**Comment by hidaen** [comment]
> **bug描述**
> 
> * *Bug description * *
>   import_export定制formats，继承ExportActionModelAdmin时，不能正常导出文件，提示未选择动作
> 
> 简单的描述下遇到的bug：
> Briefly describe the bugs encountered:
> 不能正常导出文件，提示未选择动作，且格式下拉显示的不是定制的格式，而是全部格式
> 
> **重现步骤**
> ** repeat step **
> 
> @admin.register(Test)
> class TestAdmin(ExportActionModelAdmin):
> formats = [XLS, XLSX]
> resource_class = TestResource
> 
> **环境**
> ** environment**
> 
> 1.Operating System：
> (Windows/Linux/MacOS)....
> windows
> 
> 2.Python Version：
> 3.6
> 
> 3.Django Version：
> 2.2
> 
> 4.SimpleUI Version：
> 4.0.3
> 
> **Description**

升级django-import-export吧，应该刚修复了没多久吧, django-import-export==2.3.0

**Comment by lnysky** [comment]
django-import-export升级到了2.3.0，还是存在这个问题。
定制formats时，格式列表有问题，我选择了两种格式，列表显示了所有的

**Comment by hidaen** [comment]
> 定制formats时，格式列表有问题，我选择了两种格式，列表显示了所有的

数据选中问题还要么？ 其它的我这里没调过:D

**Comment by lnysky** [comment]
可以正常导出文件，格式列表有问题，比如我定制只有两种格式，那么选择列表前两项是可以正常导出。

**Comment by newpanjing** [comment]
看下你具体的配置，以及界面截图和相关提示

**Comment by newpanjing** [comment]
使用 `ImportExportActionModelAdmin`

`ExportActionModelAdmin` 有bug 建议给django-import-export 提 issue

**Comment by OneSuperb** [comment]
研究了一天，现在只有重写actions.html的部分代码: 
1. 在simpleui的templates子目录下把 actions.html复制到自己的项目
2. 问题出现在这个html里（某个new Vue），把formats的option固定了。
 data: {
           ...............
            options: [{
                value: 0,
                label: 'csv'
          ...............
3. 把这个Vue里修改created函数：
created() {
            if (localStorage && typeof (localStorage.searchStatus) != 'undefined') {
                this.show = localStorage.searchStatus == 'true';
            }

            this.options = [];
            var file_format = []
            {% for one_format in action_form.fields.file_format.choices %}
                {% if one_format.0|safe != "" %}
                    file_format.push([{{ one_format.0|safe}}, "{{ one_format.1|safe }}"])
                {% endif %}
            {% endfor %}
            for (var file_format_i = 0; file_format_i < file_format.length; file_format_i++){
                this.options.push({value: file_format[file_format_i][0], label: file_format[file_format_i][1]})
            }
            //console.log(111,this.options)
        },
