### ISSUE TITLE
TAG 2020.7 升级后页面一片空白

### ISSUE THREAD

**Issue by hidaen** [newpanjing/simpleui#294]
<img width="785" alt="image" src="https://user-images.githubusercontent.com/4091332/89095338-7b7afb80-d3ff-11ea-8da0-9fb5addb767e.png">

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/4091332/89095381-dd3b6580-d3ff-11ea-845c-faa8cc4f1c2d.png">

这个是BUG 吗？ 提示找不到

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....

2.Python Version：
$ python --version
Python 3.7.6

3.Django Version：
VERSION = (2, 2, 1, 'final', 0)

4.SimpleUI Version：
2020.7

**Description**

**Comment by newpanjing** [comment]
提示什么？

发自我的iPhone

**Comment by hidaen** [comment]
> 提示什么？ 发自我的iPhone
> […](#)

什么都没提示，一片空白，console 中有报错

**Comment by hidaen** [comment]
应该是我这里版本的问题
