### ISSUE TITLE
可否支持django-mptt-admin树形admin显示及dashboard定制化

### ISSUE THREAD

**Issue by stevenxuwoss** [newpanjing/simpleui#295]
**你希望增加什么功能？**
** what features do you wish to add? * *
1. 支持https://pypi.org/project/django-mptt-admin/ 树形admin显示
2. 支持dashboard 定制化

**你希望哪些方面得到优化？**
1.
2.
3.

**留下你的联系方式，以便与你取得联系**
** what would you like to see optimized? * *
QQ：50036937
E-mail：youzi5201@163.com

**Comment by newpanjing** [comment]
dashboard定制化 这个可以通过重载home.html 来实现首页定制

**Comment by newpanjing** [comment]
测试版的simplepro 已经支持首页可视化定制。

demo：

http://simplepro.demo.88cto.com/

可视化定制：


http://sdc.72wo.com/
