### ISSUE TITLE
启用django debug toolbar，报错

### ISSUE THREAD

**Issue by stevenxuwoss** [newpanjing/simpleui#296]
**bug描述**
* *Bug description * * 
安装django-debug-toolbar，启用debug,报错
简单的描述下遇到的bug：
Briefly describe the bugs encountered:
SuspiciousFileOperation at /admin/
The joined path (D:\admin\simpleui-x\elementui\theme-chalk\index.css) is located outside of the base path component (D:\ssid_tcms\static)

**重现步骤**
** repeat step **
1. pip install django-debug-toolbar
2.setting 添加
if DEBUG:
    # django debug toolbar
    INSTALLED_APPS.append('debug_toolbar')
    MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')
    DEBUG_TOOLBAR_CONFIG = {
        'JQUERY_URL': '/static/jquery/3.4.1/jquery.min.js',
        # 或把jquery下载到本地然后取消下面这句的注释, 并把上面那句删除或注释掉
        #'JQUERY_URL': '/static/jquery/2.1.4/jquery.min.js',
        'SHOW_COLLAPSED': True,
        'SHOW_TOOLBAR_CALLBACK': lambda x: True,
    }

    INERNAL_IPS = ['127.0.0.1', ]
3.

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....
win 10
2.Python Version：
3.7
3.Django Version：
django 3.0.8
django-debug-toolbar               2.2
4.SimpleUI Version：
2020.7

**Description**

**Comment by newpanjing** [comment]
检查settings代码中关于 文件配置这块

**Comment by dev-liu** [comment]
同样复现，`{% static '/admin/simpleui-x/elementui/theme-chalk/index.css'` 从磁盘根目录找文件了（如`D:\admin\...`或`/admin/....`），这个文件不在static文件夹中，所以报错了，可以全局替换  `{% static '/` 为 `{% static '`
