### ISSUE TITLE
simplePro  前端actions显示异常

### ISSUE THREAD

**Issue by xojisi** [newpanjing/simpleui#297]
**环境**
1.Operating System：win10 、UBUNTU 18.04 均存在该问题
2.Python Version：3.7
3.Django Version：2.2.11
4.SimpleUI Version：4.0.3
5.SimplePro Version: 1.4

重现：
admin.py的代码部分
```
    actions = ['batchSettings']
    def batchSettings(self, request, queryset):
        try:
            ids = request.POST.get('ids').split(',')
            for id in ids:
                Batch.objects.filter(id=id, is_active=True).update(close_month=last_month(), close_year=current_year(),
                                                                   is_active=False)
            messages.add_message(request, messages.SUCCESS, "设置成功")
        except Exception as e:
            messages.add_message(request, messages.ERROR, "不支持全部选中后设置功能")
    batchSettings.short_description = "批量关闭"

    def get_actions(self, request):
        actions = super(BatchAdmin, self).get_actions(request)
        print(actions['batchSettings'])   #此处加了一个print,后续下文会提到
        return actions
```

在simplePro  \static\admin\simplepro\js\list.js  中加入一个console.
![4](https://user-images.githubusercontent.com/28687402/89152000-c24e2a00-d594-11ea-8c1c-5c806c9669e4.jpg)

测试：
重现前，先清理浏览器缓存，必须为“全部“
![6](https://user-images.githubusercontent.com/28687402/89152110-fde8f400-d594-11ea-8422-09575d85246d.jpg)

如图所示，一开始使用非超级管理员用户打开该页面，前端并未捕获到这个actions的信息，所以没有显示
同时在admin里，也没加actions的权限限制。
![1](https://user-images.githubusercontent.com/28687402/89151557-d6ddf280-d593-11ea-95e4-628381c23d24.jpg)
后台可见，这个actions的内容是有的
![2](https://user-images.githubusercontent.com/28687402/89151706-20c6d880-d594-11ea-9390-478a12827c93.jpg)
此时切换，超级管理员用户，前端依旧直接就不显示该字段了
![3](https://user-images.githubusercontent.com/28687402/89152020-cc702880-d594-11ea-9561-768a28506ed1.jpg)
后台依旧的actions依旧是正常的。
![5](https://user-images.githubusercontent.com/28687402/89152043-dabe4480-d594-11ea-8f6e-bd44aed61379.jpg)

测试结论：清理浏览器缓存后，使用非超级管理员用户打开页面，actions配置的按钮 前端无法捕获。

BUG：使用非超级管理员用户打开页面，actions配置的按钮 前端无法捕获。

**Comment by xojisi** [comment]
![10](https://user-images.githubusercontent.com/28687402/89153040-b82d2b00-d596-11ea-950b-1b39d378a13b.jpg)
正常情况，前端是可以捕获到 后端传来的actions 数据的。
但是 
清理浏览器缓存后，使用非超级管理员用户登录就无法捕获到

**Comment by xojisi** [comment]
用simpleUI试了一下，无该问题
但是simplePro依旧有。

**Comment by newpanjing** [comment]
这里有个逻辑性问题，所有非admin用户，都要配置actions的权限，才能显示。

下个版本将会修改成，没有设置权限，就默认显示。

等下个版本更新后，就不会存在此问题了。
