### ISSUE TITLE
simplepro在admin设置了autocomplete_fields时显示不正常

### ISSUE THREAD

**Issue by Luna-Papa** [newpanjing/simpleui#298]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
model 1: ChkInfo
model 2：SyncTaskInfo
model2中的字段chk_name设置了ForeignKey，关联到Chkinfo
为了实现外键自动完成，我在admin中设置了autocomplete_fields = ['chk_name']
这个设置在原生admin和simpleui中都是工作正常的，但在simplepro下显示不正常，chk_name出现了两个输入框

![微信图片_20200803162645](https://user-images.githubusercontent.com/23702103/89162581-e1ee4e00-d5a6-11ea-90db-2fac056450fe.png)
![微信图片_20200803162656](https://user-images.githubusercontent.com/23702103/89162586-e3b81180-d5a6-11ea-8518-36a6b82ad18b.png)

**环境**
** environment**

1.Operating System：Window 10
2.Python Version：3.8.3
3.Django Version：3.0.8

**Comment by newpanjing** [comment]
你admin 相关代码能不能 贴出来看下，我这 只会显示一个

![image](https://user-images.githubusercontent.com/13655483/90638746-4a545500-e260-11ea-84d8-9070dc73eebc.png)

**Comment by newpanjing** [comment]
找到原因了，下个版本 解决

**Comment by newpanjing** [comment]
simplepro的测试版已经增加了对autocomplete_fields的支持。
