### ISSUE TITLE
再提个建议啊

### ISSUE THREAD

**Issue by cncert** [newpanjing/simpleui#3]
作者你好：
在使用了你这个插件后，在首页左下角会有你项目的git地址，这个怎么去掉呢？虽然我很支持你，但如果不去掉这个地址，实在是无法应用到项目中，也不利于贵项目的推广呀。
如下：
Simpleui
项目主页:https://www.88cto.com/project/simpleui/
Github:https://github.com/newpanjing/simpleui

**Comment by newpanjing** [comment]
暂时可以用这种方法 
把所有文件复制的项目中
运行 python3 manage.py collectstatic
移除home.html中的代码地址即可。
明天我有时间的时候更新一版 去掉这个标识。

**Comment by newpanjing** [comment]
> 作者你好：
> ？在使用了你这个插件后，在首页左下角会有你项目的git的地址，这个怎么去掉呢虽然我很支持你，但如果不去掉这个地址，实在是无法应用到项目中，也不利于贵项目的推广呀。
> 如下：
> Simpleui 
> 项目主页：[https](https://www.88cto.com/project/simpleui/)：//www.88cto.com/project/simpleui/ 
> Github：[https](https://github.com/newpanjing/simpleui)：[//github.com/newpanjing/simpleui](https://github.com/newpanjing/simpleui)

哈喽，已经发布1.4.4版本了
+ 去掉了项目代码库标识
+ 还有这个bug[https://github.com/newpanjing/simpleui/issues/2](https://github.com/newpanjing/simpleui/issues/2)

如果已经安装可以直接升级
```shell
pip install django-admin --upgrade
```

**Comment by cncert** [comment]
想跟你确认下，是执行pip install django-admin --upgrade
而不是pip install django-simpleui --upgrade  对吧？
django-admin 和django-simpleui  这俩有什么区别呢？为什么安装的时候是pip install django-simpleui 呢？

**Comment by newpanjing** [comment]
打错了，是这个才对。
```python
pip install django-simpleui --upgrade
```
