### ISSUE TITLE
[bug] 用户权限问题

### ISSUE THREAD

**Issue by hackerliang** [newpanjing/simpleui#30]
**bug描述**
简单的描述下遇到的bug：
![图片](https://user-images.githubusercontent.com/32356999/57090479-78471a80-6d39-11e9-83dd-d5dc4568707c.png)
当用户组权限仅有add和view时，无法新增
![图片](https://user-images.githubusercontent.com/32356999/57090535-9c0a6080-6d39-11e9-90c9-61f583a3b12d.png)
但原生admin无此问题
![图片](https://user-images.githubusercontent.com/32356999/57090592-be03e300-6d39-11e9-9e2f-5303777558d5.png)

**重现步骤**
1.
2.
3.

**环境**

1.操作系统：windows10 home 1803
2.python版本：python3.7.3 and python 3.6.0
3.django版本：django 2.1.8 and 2.2.1
4.simpleui版本：2.0.6 and 2.1b0

**其他描述**

**Comment by newpanjing** [comment]
近期修复

**Comment by newpanjing** [comment]
已经修复该bug，请升级到2.1。
```shell
pip install django-simpleui --upgrade
```
