### ISSUE TITLE
当数据量过5W时，这里list_filter的下拉框直接爆炸

### ISSUE THREAD

**Issue by xojisi** [newpanjing/simpleui#306]
当数据量过5W时，这里list_filter的下拉框直接爆炸
是否可以优化一下？
为考虑性能，如果超过50条，那么就没有下拉框了，就变成一个输入搜索框。
实际上超过50条，你选其中一个也比较痛苦，虽然支持搜索查找
![image](https://user-images.githubusercontent.com/28687402/92547401-60fe3280-f287-11ea-9ae4-5552c52b2dcf.png)

**Comment by newpanjing** [comment]
后续会进行优化。

**Comment by newpanjing** [comment]
这个你可以先试用search_fields进行配置，下拉框也不方便进行限制，影响比较大。

**Comment by bijack** [comment]
> 后续会进行优化。

在不用simpleui时，可以自定义输入搜索框应对下拉数据太多的列，但用上simpleui后自定义的输入搜索框就生效了，simpleui可否支持下自定义输入搜索框？
