### ISSUE TITLE
menu不向用户展示没有权限的name

### ISSUE THREAD

**Issue by FangZiyong** [newpanjing/simpleui#307]
**你希望增加什么功能？**
** what features do you wish to add? * *
1.menu栏根据用户是否有相应的权限，如果用户没有相应model的权限，不展示对应的名称

**Comment by newpanjing** [comment]
django支持权限功能，你只要设置了权限，menu就不会根据权限来。具体的可以查阅django权限部分。自定义菜单也同样支持权限，仅限simplepro。
