### ISSUE TITLE
定时刷新页面

### ISSUE THREAD

**Issue by Just1nWang** [newpanjing/simpleui#308]
**你希望增加什么功能？**
1. 列表页面支持设置当前页面定时刷新的频率
2. admin.ModelAdmin支持默认的刷新频率的属性，默认行为为不刷新。

**留下你的联系方式，以便与你取得联系**
E-mail：beyondonehour@gmail.com

**Comment by newpanjing** [comment]
这种业务性功能，simpleui暂时不考虑支持

不过你可以写个baseAdmin来让所有admin继承，非常简单。

参考地址：

https://blog.csdn.net/songhao8080/article/details/103669945
