### ISSUE TITLE
数据显示问题

### ISSUE THREAD

**Issue by Weibw162** [newpanjing/simpleui#31]
admin中只要使用了TabularInline类的都会出现排版问题
示例1
![image](https://user-images.githubusercontent.com/43693541/57434609-e75acc80-726d-11e9-8e84-51bd7064bf6c.png)
示例2
![issue2](https://user-images.githubusercontent.com/43693541/57434937-b3cc7200-726e-11e9-9067-889085d0ea5f.PNG)

下面是原生admin的截图
![issue3](https://user-images.githubusercontent.com/43693541/57434973-ce9ee680-726e-11e9-9420-96aa510a8ddc.PNG)
![issue4](https://user-images.githubusercontent.com/43693541/57434989-d6f72180-726e-11e9-9f64-e81cde91fcf8.PNG)
可以看出来原生的是没有这个问题的。

**Comment by newpanjing** [comment]
你咋配置的，代码发来看看，我配置的貌似显示正常。
![image](https://user-images.githubusercontent.com/13655483/57996686-6fa56100-7afb-11e9-9489-471f1a3a95fb.png)

**Comment by wuchencm** [comment]
我也出现了相同的问题，貌似是重复的展示了 
def __str__(self):
      return self.name

**Comment by newpanjing** [comment]
@wuchencm 贴个图看看。

**Comment by newpanjing** [comment]
已经修复了此问题，请更新至2.1.2
```shell
pip install django-simpleui -U
```

@Weibw162 @wuchencm
