### ISSUE TITLE
自定义action涉及数据库更新时操作无效

### ISSUE THREAD

**Issue by qiuzige** [newpanjing/simpleui#311]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:
在admin.py新增一个action，实现点击一下按钮更新数据的功能，该action无效

**重现步骤**
** repeat step **
1.新增action
2.在界面能产生button，但是没有功能
3.在settings关闭simpleui，使用原生django，改功能没有问题
![1600762739188](https://user-images.githubusercontent.com/52486559/93858868-6891f280-fcef-11ea-8cb2-ff5e03f72f3c.jpg)
![1600762880062](https://user-images.githubusercontent.com/52486559/93859055-b27ad880-fcef-11ea-922a-65b47e837f4b.jpg)

**环境**
** environment**

1.Operating System：Ubuntu18
(Windows/Linux/MacOS)....

2.Python Version：3.6.9

3.Django Version：3.0.8

4.SimpleUI Version：今年8月的时候在官网下载使用源码安装的，不知道版本号

**Description**

**Comment by newpanjing** [comment]
升级到最新版，

自定义按钮文档：

https://simpleui.88cto.com/docs/simpleui/QUICK.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8C%89%E9%92%AE-action
