### ISSUE TITLE
字体大小问题

### ISSUE THREAD

**Issue by lanheader** [newpanjing/simpleui#312]
**bug描述**
* *Bug description * * 
页面字体默认12px，实际大小16px

简单的描述下遇到的bug：
Briefly describe the bugs encountered:
页面字体实际为16px，但是字体大小设置显示当前字体为12px。
**重现步骤**
** repeat step **
1.将字体设置拖动到最左侧字体设置为12px
2.点击重置字体恢复至16px。

**环境**
** environment**
1.Operating System：
(Windows/Linux/MacOS)....

2.Python Version：
python3.7
3.Django Version：
diango3.0.3
4.SimpleUI Version：
simpleui 2020.9

**Description**

**Comment by newpanjing** [comment]
simpleui 使用的第三方的组件，在默认情况下，每个组件 字体大小都是不一样的，我们没有强制设置为12px，只有在调整字体的时候才强制设置。这是为了兼容考虑。
