### ISSUE TITLE
2020.09.26版本无法保存筛选项

### ISSUE THREAD

**Issue by strawberry224** [newpanjing/simpleui#314]
之前的 2020.07 版本筛选之后，点击进入编辑页，点击回退按钮重新回到搜索页面后，之前的筛选项还是保留的，但是更新到 2020.09.26 版本之后每次从编辑页回退筛选项都会被清空。

**Comment by strawberry224** [comment]
2020.07版本回退的代码是：
`goBack: function () {
    window.location.href = '{% get_previous_url %}'
 }`

2020.09.26版本回退的代码是：
`goBack: function () {
    window.location.href = '{% get_model_url %}'
}
`

有什么用意吗，但是我现在每次处理某种过滤条件的多条结果时，每查看一条就要重新过滤一次，体验真的很差

**Comment by newpanjing** [comment]
近期将会验证这个问题
