### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by xojisi** [newpanjing/simpleui#316]
建议1：
是否考虑在simplePro列表页上，直接做行内新增的功能
而不是直接的跳转到一个 新增的页面。

建议2：
有些页面，数据比较长，我想将这个操作的列去掉（修改、删除），体验更好些。
有些页，数据少，我又想显示出来。
![image](https://user-images.githubusercontent.com/28687402/95938191-f1421100-0e0b-11eb-93e5-352d7c4b3bb2.png)
但当前的配置是一刀切，比较麻烦

**Comment by newpanjing** [comment]
这个操作列是可以去掉的，可以看文档配置，另外 只要配置了list_editable之后 可以弹框编辑。行内增加和编辑 会存在一个性能问题，导致操作比较卡。暂时只能等待后续想办法解决。

**Comment by lsshu** [comment]
admin/css/responsive.css 547行   .aligned .form-row > div {width: calc(100vw - 40px);}

**Comment by Ehco1996** [comment]
@newpanjing 请我能想django-jet 一样提供一下dashboard 或者charts么

**Comment by newpanjing** [comment]
1. 行内新增无法兼容插件，理论上实现是没问题

2.  编辑和删除这个按钮是可以在admin中配置显示和隐藏的 `actions_show=False`

[https://simpleui.72wo.com/docs/simplepro/table.html](
https://simpleui.72wo.com/docs/simplepro/table.html)
