### ISSUE TITLE
Simpletags not defined

### ISSUE THREAD

**Issue by leogout** [newpanjing/simpleui#319]
**Bug description**
Invalid template library specified. ImportError raised when trying to load 'simpleui.templatetags.simpletags': No module named 'simpleui.templatetags'

This happens with the new version of simpleUI (2020.9.26) and not with the older version (2020.7).

**Repeat step**
1. pip install django-simpleui
2. Go to localhost:8000/admin

**Environment**
_Operating System_：Windows
_Python Version_：3.7
_Django Version_：2.2
_SimpleUI Version_：2020.9.26

Sorry I don't speak Chinese, but I will try to help as much as I can :)

**Comment by mlzboy** [comment]
also got this problem

**Comment by newpanjing** [comment]
Remove the virtual environment, reinstall Django-Simpleui, and restart the project.
请删除虚拟环境，重新安装django-simpleui，然后重启项目即可。
