### ISSUE TITLE
2.0版本多对多字段无法保存

### ISSUE THREAD

**Issue by duxiaoyang06** [newpanjing/simpleui#32]
**bug描述**
简单的描述下遇到的bug：

**重现步骤**
1.a表字段
2.b表字段ManytoManya表字段
3.详情页保存b的时候，b的多对多字段值被清空，无法保存

**环境**

1.操作系统：mac 10.12
2.python版本：3.6
3.django版本：2.0.2
4.simpleui版本：2.0

**其他描述**

**Comment by newpanjing** [comment]
@duxiaoyang06 详细描述下bug
