### ISSUE TITLE
首页快捷操作显示问题

### ISSUE THREAD

**Issue by eshxcmhk** [newpanjing/simpleui#322]
**你希望哪些方面得到优化？**
1.首页中的快捷操作模块中，条目的文字标题显示可以折行显示，或者通过配置选项开启折行显示。

**留下你的联系方式，以便与你取得联系**
E-mail：935057137@qq.com

**Comment by newpanjing** [comment]
这个暂时不考虑，换行显示会导致图标排版错乱
