### ISSUE TITLE
使用django-import-export 这个插件  勾选内容的情况下  导出、导入两个按钮功能都变成删除数据

### ISSUE THREAD

**Issue by 68110923** [newpanjing/simpleui#326]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:

**重现步骤**
** repeat step **
1.
2.
3.

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....

2.Python Version：3.7.9

3.Django Version：3.1.4

4.SimpleUI Version：2021.1.1

**Description**

**Comment by ruizeng2018** [comment]
我也遇到了，一摸一样

**Comment by newpanjing** [comment]
有截图吗？

**Comment by wxxiao** [comment]
我也遇到了同样的问题

如果列表勾选了某一条记录  点击导入按钮  提示删除勾选的记录

**Comment by 68110923** [comment]
> 有截图吗？

有视频，发群里了

**Comment by CinFree** [comment]
> 有截图吗？

我提交了修复，你拉一下

**Comment by newpanjing** [comment]
2021.4 中解决该bug
