### ISSUE TITLE
list_filter支持多选

### ISSUE THREAD

**Issue by twinkle316** [newpanjing/simpleui#327]
**你希望增加什么功能？**
** what features do you wish to add? * *
1.django默认list_filter支持单选,如何支持多选?

**留下你的联系方式，以便与你取得联系**
** what would you like to see optimized? * *
E-mail：twinkle316@gmail.com

**Comment by newpanjing** [comment]
由于django的限制，在simpleui中无法做到多选的功能，我们已经把多选加入到simplepro中，在即将发布的simplepro3.x版本中就会加入list_filter多选的支持。
```python
class Admin():
   def get_list_filter_multiples(self,request):
      return ('field1','field2')

```

or

```python

class Admin():
    list_filter_multiples=('field1','field2')

```
