### ISSUE TITLE
关于修改SIMPLEUI_LOGO自定义logo的问题

### ISSUE THREAD

**Issue by ShiningSYK** [newpanjing/simpleui#33]
**bug描述**
简单的描述下遇到的bug：

**重现步骤**
1.修改settings中的SIMPLEUI_LOGO的值，即图片的url
2.我将图片放在了项目包的一级目录下
3.SIMPLEUI_LOGO = os.path.join(BASE_DIR,'logo1.png')

**环境**

1.操作系统：win10
2.python版本：py37
3.django版本：2.2.1
4.simpleui版本：2.0.6

**其他描述**
使用 Ctrl+选中url 的快捷方式可以打开图片，说明不是路径的问题
显示图片破裂应该是未找到图片？
![image](https://user-images.githubusercontent.com/45619625/57583118-ce694a00-74ff-11e9-9f4c-ec150c9ad004.png)我看到的效果如图
我又按照demo中使用图片的大小，60×60px，重新设置了logo的大小，还是无法正常显示

**Comment by newpanjing** [comment]
图片路径是http访问的路径，不是文件系统的路径：
例如你项目结构如下：

aaa_project
 ---aaa_project
 ---templates
 ---static
 -----logo.png

在settings.py中配置静态目录为static

配置simpleui的logo
> SIMPLEUI_LOGO=/static/logo.png

http的访问路径为：
你的域名.com/static/logo.png

**Comment by ShiningSYK** [comment]
多谢楼主解答
