### ISSUE TITLE
重要!!!!!!!!揭露作者诈骗过程

### ISSUE THREAD

**Issue by KevinMyDing** [newpanjing/simpleui#330]
我方公司于2020年12月1日向作者购买了simplepro的源代码,共计6688元整,作者以压缩包的形式发送给我方,在作者官网上,写着如下信息:

![image](https://user-images.githubusercontent.com/10447540/103146825-b5231900-4789-11eb-9ff2-64446bcda4b2.png)

而作者于2020年12月10日失联,所有问题均不回复,我方于2020年12月26日发现已被拉黑.

作者姓名: 潘敬
公司: 深圳市十二点科技有限公司
账号: 7559 4971 5410 902

以下为付款及聊天记录:

![image](https://user-images.githubusercontent.com/10447540/103146987-65dde800-478b-11eb-9811-37f13f517250.png)
![image](https://user-images.githubusercontent.com/10447540/103146994-78582180-478b-11eb-8b8a-42565e027a4f.png)

![image](https://user-images.githubusercontent.com/10447540/103147023-c0774400-478b-11eb-946f-dca28dd6d127.png)

**Comment by newpanjing** [comment]
去报警吧，给你重开发票了，你说周一财务会安排转给我，都过了多少个周一了。
不想给钱还想白嫖。

**Comment by KevinMyDing** [comment]
6688给了 居然还叫白嫖 厉害了

**Comment by newpanjing** [comment]
源码通过邮件已经发送给你了，后面你申请开票，也开了发票给你。截图为证。

然后你说 你们那边资料填写错误，需要补开个发票，这是你们造成的问题，税费由你们承担。
补开票你说周一财务安排给我，我催促3次，你都说催催财务。

这是你自己言而无信在先，现在你还恬不知耻的厚着脸皮说我诈骗。
我没去报警说你诈骗我一张6688的发票，已经很给你面子了。

你聊天记录截图发上来可以，为什么没勇气上传完整的聊天记录呢？

在网上当键盘侠 没任何意义，我都已经不追究你诈骗我6688的发票，你却在网上造谣我诈骗。

根据《中华人民共和国治安管理处罚法》第八条
”违反治安管理的行为对他人造成损害的，行为人或者其监护人应当依法承担民事责任。“

如果你再继续造谣，我们将报警处理，且不接受调节与谅解。

如果你不服，有本事报警，咱们在网上直播全过程。


![IMG_0796](https://user-images.githubusercontent.com/13655483/103153778-ede4e180-47cd-11eb-8784-d4abf9a1ec65.PNG)
<img width="1190" alt="aaa" src="https://user-images.githubusercontent.com/13655483/103153784-f63d1c80-47cd-11eb-8c7c-62fc2155ffbb.png">

**Comment by newpanjing** [comment]
@KevinMyDing 别怂 上证据 继续

**Comment by KevinMyDing** [comment]
哦?原来作者的理论是,遇到问题不解决,而是删除拉黑?    
你的长期支持在哪里?付费的结论是没有更新?购买之前承诺的更新在哪里?你想报警随你报 收了钱删人还能有理?    
已发送的聊天记录还不能证明吗?    
您的意思是说,我们服了6688元,于是舍不得给你200元???    
那您还是报警吧,我们确实不怕事大.

**Comment by KevinMyDing** [comment]
建议作者好好看一下法律,开票要我付税费,还说要报警,您真厉害啊

**Comment by newpanjing** [comment]
补开发票不用付税？强盗逻辑

发自我的iPhone
