### ISSUE TITLE
多标签标题更新错乱

### ISSUE THREAD

**Issue by eshxcmhk** [newpanjing/simpleui#331]
**bug描述**
* *Bug description * * 
* 打开多个model标签（`首页`、`A`、`B`）后，在`A`标签刷新时马上切换到`B`标签，之后`A`标签刷新完成更新标签标题时，新标题名称被更新到`B`标签，`A`标签的标题未变；
* 打开多个model标签（`首页`、`A`、`B`）后，`A`标签页面点击任意一个条目进入详情页面，加载完成后，切换到`首页`标签，快捷操作中`A`标签对应model的文本标题变更为`A`标签的标题。

**环境**
** environment**

1.Operating System：Centos 6

2.Python Version：3.7.4

3.Django Version：2.2.17

4.SimpleUI Version：2021.1.1

**Comment by 68110923** [comment]
同
