### ISSUE TITLE
Select all选择全部之后 删除功能和导出数据功能 后端只能接收到当前页的obj

### ISSUE THREAD

**Issue by 68110923** [newpanjing/simpleui#332]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:
Select all选择全部之后 删除功能和导出数据功能bug 后端只能接收到当前页的obj

**重现步骤**
** repeat step **
1.Select all选择全部数据   多页
2.删除或导出选择的数据
3.bug表现为：实际删除或导出的数据只有全选时，当前页的数据

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....
Windows，Linux

2.Python Version：3.7.9

3.Django Version：2.2.8，3.1.5

4.SimpleUI Version：2021.1.0，2021.1.1，2020.9.26

**Description**

**Comment by newpanjing** [comment]
你后端怎么接受的？

**Comment by KingJeeWhy** [comment]
> 你后端怎么接受的？

Python Version: 3.7.3
Django Version: 2.1.4
SimpleUI Version: 2020.07
Django-import-export Version: 2.3.0


我出现了跟他一样的ISSUE，是使用了Django-import-export插件的Django继承管理时出现的（没有测试直接使用admin.ModelAdmin的情况）。
当admin.py继承ImportExportModelAdmin时，全选删除将只会删除当前页 失败率100%
当admin.py继承ImportExportActionModelAdmin时：
1、直接全选，删除所有数据正常
2、直接全选，导出默认xls格式Excel数据正常
3、全选，更换格式为xlsx(或者其他)格式，导出Excel，导出仅当前页数据
5、全选，更换格式为xlsx(或者其他)格式，点击删除，仅删除当页数据
7、更换格式为xlsx（或者其他）格式，全选，点击导出，导出所有数据正常
8、更换格式为xlsx（或者其他）格式，全选，点击删除，删除全部数据正常
9、全选，更换格式为xlsx(或者其他)格式，取消全选，重新全选，导出所有数据正常
10、全选，更换格式为xlsx(或者其他)格式，取消全选，重新全选，删除所有数据正常
结论：
1）先选择导出格式（或者不更改格式），然后全选导出或者删除功能正常
2）先全选，然后更改导出格式，再导出或者删除将仅导出或删除当前页

**Comment by RunningFaster** [comment]
遇到一样的问题。submit提交form时只能获取到当前页面的数据信息

**Comment by RunningFaster** [comment]
建议方案：阻止默认的form提交，重写 根据长度信息重写 form > data 内的 queryset信息

**Comment by ydf** [comment]
https://github.com/newpanjing/simpleui/pull/345  已经修复好了
