### ISSUE TITLE
templatetags/simpletags.py/handler_eid函数bug

### ISSUE THREAD

**Issue by byte1byte** [newpanjing/simpleui#339]
**templatetags/simpletags.py/handler_eid函数bug**
* *Bug description * * 

简单的描述下遇到的bug：
造成tab页id重复，不能正常切换tab页，需修改成如下：
def handler_eid(data, eid):
    for i in data:
        eid += 1
        i['eid'] = eid
        if 'models' in i:
            eid = handler_eid(i.get('models'), eid) 
    return eid

**Comment by newpanjing** [comment]
十分感谢，修复了，可以直接push代码到我们仓库中哈。
