### ISSUE TITLE
来自菜鸟的期望

### ISSUE THREAD

**Issue by ShiningSYK** [newpanjing/simpleui#34]
**你希望增加什么功能？**
1.可以修改admin展示表单的字体大小
2.可以拉伸所展示表单的每一列的宽度
3.增加邮箱/验证码/手机验证码 验证体系

**你希望哪些方面得到优化？**
1.
2.
3.

**留下你的联系方式，以便与你取得联系**
QQ：1052303323
邮箱：1052303323@qq.com

**Comment by newpanjing** [comment]
1.可以修改admin展示表单的字体大小
2.1中准备加入字体大小调整。
2和3 后续版本考虑加入。

**Comment by newpanjing** [comment]
已经修复该bug，请升级到2.1。
```shell
pip install django-simpleui --upgrade
```
