### ISSUE TITLE
search_fields 支持多表单

### ISSUE THREAD

**Issue by xiaoqiao99** [newpanjing/simpleui#348]
**你希望增加什么功能？**
** what features do you wish to add? * *
1. search_fields 可以支持多表单 and搜索

**留下你的联系方式，以便与你取得联系**
** what would you like to see optimized? * *
QQ：648521746
E-mail：erlangshenzun@163.com

**Comment by newpanjing** [comment]
这个功能要等django的支持，建议去django仓库反馈。
