### ISSUE TITLE
内联数据UI页面数据重复

### ISSUE THREAD

**Issue by KevinJonesChs** [newpanjing/simpleui#350]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
使用admin.TabularInline内联时，展示的内联数据重复

**重现步骤**
** repeat step **
1.创建两张表
2.使用admin自带内联 admin.TabularInline增加关联关系
3.admin登录后，录入内联数据时显示两份录入信息

**环境**
** environment**

1.Operating System：macos11.2.2
2.Python Version：3.9
3.Django Version：3.1.7
4.SimpleUI Version：2021.4.1

**Description**

**Comment by KevinJonesChs** [comment]
`class taskinline(admin.TabularInline):
    model = taskinfo
    extra = 1

@admin.register(projectinfo)
class projectinfoAdmin(admin.ModelAdmin):
    list_display = (
        'id',
        'name',
        'note',
        'implementer',
        'pmuser',
        'pmphone',
        'ourpmuser',
        'startdate',
        'enddate',
        'createdate',
        'createtime',
        'createby',
        'updatedate',
        'updatetime',
        'updateby',
    )
    list_display_links = (
        'id',
        'name',
    )
    list_per_page = 30

    inlines = [
        taskinline,
    ]

#内联表单数据保存
    def save_formset(self, request, form, formset, change):
        instances = formset.save(commit = False)
        for instance in instances:
            instance.createby = request.user
            instance.save()
        formset.save_m2m()

# 保存数据
    def save_model(self, request, obj, form, change):
        if change:  # 判断本次提交是否是更新
            obj.updateby = request.user
        else:
            obj.createby = request.user
        super().save_model(request, obj, form, change)`

**Comment by newpanjing** [comment]
simpleiu支持皮肤 不做具体功能的处理

**Comment by newpanjing** [comment]
simpleui只是皮肤 不做具体功能的处理
