### ISSUE TITLE
Timezone is set fixed to +08:00

### ISSUE THREAD

**Issue by macmoritz** [newpanjing/simpleui#351]

**Comment by newpanjing** [comment]
1. USE_TZ = TRUE OR USE_TZ = FALSE

2. Issue format is incorrect

**Comment by macmoritz** [comment]
When using **USE_TZ =True** simpleui uses the timezone +08:00.
This timezone is used for example in the search form of a Model.
The fixed timezone can be found in
simpleui/templatetags/simpletags.py at line 460.
