### ISSUE TITLE
分页缺少一页数据，不能选第一页

### ISSUE THREAD

**Issue by goeswell** [newpanjing/simpleui#361]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:
分页有问题，使用原生django admin 分页没有问题，安装simpleui后，不能从第一页开始翻页，
点选第一页，还是在第二页位置

**重现步骤**
** repeat step **
1.使用原生admin，分页正常
2.安装simpleu
3.重新打开页面，分页只能从第二页开始

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....
windows 10 64位
2.Python Version：
python 3.8
3.Django Version：
Django 3.2
4.SimpleUI Version：
2021.1.0

**Description**

**Comment by xzxjysgd** [comment]
我也遇到了同样的问题  ：分页有问题，使用原生django admin 分页没有问题，安装simpleui后，不能从第一页开始翻页，
点选第一页，还是在第二页位置

**Comment by egoisz** [comment]
我也遇到了同样的问题 ，使用原生django admin 分页没有问题

**Comment by AbelChe** [comment]
我也遇到了相同的问题，翻看simpleui的模版的源码，发现是分页的前端页数计算方式出错了。。。
需要在修改第9行` :current-page="{{ cl.page_num }}+1"`和第23行`page_go(page-1);`修改页数计算方式，具体修改为如下：
```html
...
                @current-change="handleCurrentChange"
                :current-page="{{ cl.page_num }}"
                :page-size="{{ cl.list_per_page }}"
                layout="total,prev, pager, next, jumper"
                :total="{{ cl.result_count|to_str }}">
        </el-pagination>
...
            methods: {
                handleCurrentChange:function (page) {
                    page_go(page);
                }
            }
...
</script>
```

**Comment by Allo-0** [comment]
我这按你这改了也没用😭

**Comment by jackuboot** [comment]
去掉+1和-1即可
