### ISSUE TITLE
actions.js addEventListener报错

### ISSUE THREAD

**Issue by goeswell** [newpanjing/simpleui#362]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at window.Actions (actions.js:128)
    at HTMLDocument.<anonymous> (actions.js:167)

**重现步骤**
** repeat step **
1.安装最新版simpleui
2.打开浏览器，访问查询数据页面
3.控制台报错，但不知道是否对功能照成影响

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....
win10 64位
2.Python Version：
3.8
3.Django Version：
3.2
4.SimpleUI Version：
2021.4.1

**Description**

**Comment by brownfoxsir** [comment]
我也遇到这个bug了,好像在django2.2上也能复现这个问题，记不太清了
环境和楼主的一样
consloe控制台输出：
```
GET http://127.0.0.1:8000/static/admin/simpleui-x/theme/None net::ERR_ABORTED 404 (Not Found)

Uncaught TypeError: Cannot read property 'addEventListener' of null
    at window.Actions (actions.js:128)
    at HTMLDocument.<anonymous> (actions.js:167)
window.Actions @ actions.js:128
(anonymous) @ actions.js:167

```
这个文件是Django的源码文件在```django/contrib/admin/static/admin/js/actions.js```
临时解决方案： （可以在collectstatic后在项目的static目录下修改，也可以直接修改源码）
```
        if (document.querySelector('#changelist-form button[name=index]') != null) {
            document.querySelector('#changelist-form button[name=index]').addEventListener('click', function () {
                if (list_editable_changed) {
                    const confirmed = confirm(gettext("You have unsaved changes on individual editable fields. If you run an action, your unsaved changes will be lost."));
                    if (!confirmed) {
                        event.preventDefault();
                    }
                }
            })
        }
```

# 但是我一直遇到这个问题 不知道有没人见过，如何处理？看得我有点难受 
```
GET http://127.0.0.1:8000/static/admin/simpleui-x/theme/None net::ERR_ABORTED 404 (Not Found)
```
为什么要去查找这个东西啊？？？搞不懂一直找不到。。。。。
