### ISSUE TITLE
希望支持数据表页面自动刷新

### ISSUE THREAD

**Issue by cnstark** [newpanjing/simpleui#369]
**你希望增加什么功能？**
** what features do you wish to add? * *
1.
2.
3.

**你希望哪些方面得到优化？**
1.
2.
3.

**留下你的联系方式，以便与你取得联系**
** what would you like to see optimized? * *
QQ：915778455
E-mail：yuhaow97@gmail.com

**Comment by newpanjing** [comment]
可以自己在admin的meta中引入个js 定时刷新即可。
