### ISSUE TITLE
django-import-export 导入数据时js控制台报错

### ISSUE THREAD

**Issue by brownfoxsir** [newpanjing/simpleui#370]
**bug描述**
* *Bug description * * 
![image](https://user-images.githubusercontent.com/38450626/117452401-4e530f00-af76-11eb-9798-ab8129aa7609.png)

简单的描述下遇到的bug：
只要有导入这个action，点开控制台就报错了
**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....

2.Python Version：3.8

3.Django Version：3.2.2

4.SimpleUI Version：2021.4.3

**Description**

**Comment by newpanjing** [comment]
升级到2021.5.11
