### ISSUE TITLE
为什么要为td.original设置-50的margin-top呢？

### ISSUE THREAD

**Issue by yanhuixie** [newpanjing/simpleui#372]
https://github.com/newpanjing/simpleui/blob/c5fdc1b7a1cda33b240e73f62bffa48ff0ce00d5/simpleui/templates/admin/change_form.html#L14

这样会导致original的显示位置错乱。见图：
![Dingtalk_20210513134400](https://user-images.githubusercontent.com/1049615/118083395-681aa900-b3f1-11eb-9ef3-6517d0b1a85d.jpg)

港真我很不理解django为何要设计“inline original”这么一个东西，食之无味弃之可惜，官版的显示效果就很不友好，对于英文基本还能看，一旦有中文，就会被腰斩，只能显示半截了。对于官版的样式，覆盖一下base_site.html的样式，把height从1.2em改成1.5em就基本够用。只是在simpleui中，对于这个样式的处理有点不理解，一刀切 -50 margin-top可能适应性会比较弱呢。

**Comment by newpanjing** [comment]
不同django版本造成的。提issue 安装模板格式来。
