### ISSUE TITLE
分页默认显示第二页，第一页无法跳转

### ISSUE THREAD

**Issue by egoisz** [newpanjing/simpleui#374]
1.Operating System：
(Windows/Linux/MacOS)....
Windows + Linux
2.Python Version：
3.7.8
3.Django Version：
3.2
4.SimpleUI Version：
2021.5.11

**Description**
分页默认显示第二页，第一页无法跳转

**Comment by sigma-plus** [comment]
方法一：升级Django版本

方法二：在修改simpletags.py中最后一个函数
@register.simple_tag
def django_version_is_gte_32x():
    arrays = django.get_version().split(".")
    version = []
    for s in arrays:
        version.append(int(s))

    return tuple(version) >= (3, 2, 0) # 这个左边是(3,2)时，返回False, 实际上应该返回True
最后一句修改为：
return tuple(version) >= (3, 2)
