### ISSUE TITLE
admin批量删除没显示具体外键

### ISSUE THREAD

**Issue by lin-peidong** [newpanjing/simpleui#377]
**admin批量删除没显示具体外键**
多选删除的话，直接弹出框里点确定就删掉了，也不知道具体删除了啥
一个一个删除没有此问题

**Comment by lin-peidong** [comment]
![Uploading image.png…]()

**Comment by lin-peidong** [comment]
![image](https://user-images.githubusercontent.com/27152007/118467321-46ddf380-b736-11eb-9d53-24c11d08e1b0.png)

**Comment by newpanjing** [comment]
可以用回默认django

**Comment by lin-peidong** [comment]
pro 会这样吗？不会的话考虑买pro，这个等于废了批量删除功能
