### ISSUE TITLE
添加filter之后列表页存在样式bug

### ISSUE THREAD

**Issue by Star-fly-Cheng** [newpanjing/simpleui#379]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:
添加filter之后列表页存在样式bug
比如https://www.88cto.com/admin/#/admin/article/article/
![企业微信20210525-113638](https://user-images.githubusercontent.com/33115681/119435809-85cf0300-bd4d-11eb-8785-0b0af0d6c62b.png)

但是没有filter只有search的列表页是正常的比如https://www.88cto.com/admin/#/admin/article/member/
![image](https://user-images.githubusercontent.com/33115681/119435845-9a130000-bd4d-11eb-816c-08c69313a0aa.png)

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS）

2.Python Version：3.8

3.Django Version：2.2

4.SimpleUI Version：3.0

**Description**

**Comment by newpanjing** [comment]
升级到最新版
