### ISSUE TITLE
登录页打不开的bug

### ISSUE THREAD

**Issue by Stronese** [newpanjing/simpleui#380]
碰到登录页打不开的问题，将simpleui/templates/admin/login.html  98行的translate前后的{% %}删掉后恢复正常了

Error during template rendering

In template /usr/local/lib/python3.8/site-packages/simpleui/templates/admin/login.html, error at line 98
Invalid block tag on line 98: 'translate', expected 'elif'，'else' or 'endif'. Did you forget to register or load this tag?

98行代码如下
<a class="forgot-password" href="{{ password_reset_url }}">{% translate 'Forgotten your password or username?' %}</a>

django 2.2   python3.8

Request Method: | GET
-- | --
http://localhost:8001/admin/login/
2.2
TemplateSyntaxError
Invalid block tag on line 98: 'translate', expected 'elif'，'else' or 'endif'. Did you forget to register or load this tag?
/Users/zhangqiang/Library/Python/3.8/lib/python/site-packages/django/template/base.py in invalid_block_tag, line 522
/usr/local/opt/python@3.8/bin/python3.8
3.8.6
['/Users/zhangqiang/Documents/codeFile/corgi',  '/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',  '/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8',  '/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload',  '/Users/zhangqiang/Library/Python/3.8/lib/python/site-packages',  '/usr/local/lib/python3.8/site-packages']
星期日, 30 五月 2021 17:20:19 +0800

**Comment by newpanjing** [comment]
django卸载重装，然后重新启动项目

**Comment by cupid5trick** [comment]
Django2.2的话可能是版本的问题，低版本(3.0及以下)没有translate这个template tag，我之前遇到过。
[Django3.2的i18n模板翻译语法](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#translate-template-tag)
[Django3.0的i18n模板翻译语法](https://docs.djangoproject.com/en/3.0/topics/i18n/translation/#trans-template-tag)
[Django2.2的i18n模板翻译语法](https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#trans-template-tag)

**Comment by newpanjing** [comment]
升级到最新版就可以了
