### ISSUE TITLE
ManyToManyField  显示优化

### ISSUE THREAD

**Issue by qingchunyouni** [newpanjing/simpleui#382]
**你希望哪些方面得到优化？**
1.ManyToManyField 在simpleui 界面输出显示是以逗号分隔的，可以以自动换行的方式实现吗
![E3V Y0OIP2J`4RM$CIS DU2](https://user-images.githubusercontent.com/58733140/120913768-1c93ac00-c6cc-11eb-9ed1-718a0c83af12.png)
**留下你的联系方式，以便与你取得联系**
** what would you like to see optimized? * *
E-mail：897117582@qq.com

**Comment by newpanjing** [comment]
后期的版本可以考虑加入标签显示外键，直接读取对象的__str__方法，通过重写 这个方法就可以实现想要显示的字段。

**Comment by newpanjing** [comment]
由于django的限制，多对多字段，simplepro暂时无法处理，建议自己增加自定义的列来实现 显示样式调整。
