### ISSUE TITLE
simplepro 使用组件simplepro.components.fields定义的models 在admin使用TabularInline，StackedInlin时无法编辑

### ISSUE THREAD

**Issue by KevinJonesChs** [newpanjing/simpleui#385]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:

**重现步骤**
** repeat step **
1.
2.
3.

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....

2.Python Version：

3.Django Version：

4.SimpleUI Version：

**Description**

**Comment by KevinJonesChs** [comment]
![image](https://user-images.githubusercontent.com/68941234/121625363-eb3d2680-caa5-11eb-8104-436c01f8066c.png)
![image](https://user-images.githubusercontent.com/68941234/121625395-fb550600-caa5-11eb-8ed3-951b15a77f7f.png)
![image](https://user-images.githubusercontent.com/68941234/121625604-5be44300-caa6-11eb-890f-3e70a836bc25.png)

**Comment by newpanjing** [comment]
在版本3.0.3中修复次bug，更新即可。在版本3.0.3中修复次bug，更新即可。
