### ISSUE TITLE
在 raw_id_fields的模式下,弹出选择清单后, 如果点搜索后, 会选择不了

### ISSUE THREAD

**Issue by JohnYan2017** [newpanjing/simpleui#39]
在 raw_id_fields的模式下,弹出选择清单后, 如果点搜索后, 会选择不了, 直接会跑到编辑页面
发现在是在点搜索后页面刷新了, url之前的带&_popup=1, 刷新没有这个了

**重现步骤**
1. 采用raw_id_fields
2. 弹出选择框
3. 筛选一项, 后就无法选择要的项目

**环境**

1.操作系统：
2.python版本：3.6
3.django版本：2.1
4.simpleui版本：2.0

**其他描述**

**Comment by newpanjing** [comment]
搜索之后丢失了2个参数_to_field和_popup，下个版本修复。

**Comment by newpanjing** [comment]
已经修复该bug，请升级到2.1。
```shell
pip install django-simpleui --upgrade
```
