### ISSUE TITLE
为SIMPLEUI_CONFIG中menus适配权限控制

### ISSUE THREAD

**Issue by kkAct** [newpanjing/simpleui#396]
**你希望哪些方面得到优化？**
> 现有的SIMPLEUI_CONFIG中的menus可以满足菜单栏的个性化配置, 但没有适配djang admin的权限控制
> 希望在保留个性化配置的同时可以适配权限控制

ps: 这是我看到的类似功能实现的博客 https://www.jianshu.com/p/0d1175a43186

**留下你的联系方式，以便与你取得联系**
E-mail：hashzhao@gmail.com

**Comment by newpanjing** [comment]
可以创建PR 合并到dev分支中。
