### ISSUE TITLE
图标优化

### ISSUE THREAD

**Issue by HenryJi529** [newpanjing/simpleui#397]
**你希望增加什么功能？**
1.  fontawesome版本更新[4.7]或者支援[fontawesome cdn设置](https://cdn.fontawesome.com/embed-codes)

**你希望哪些方面得到优化？**
1. 图标

**留下你的联系方式，以便与你取得联系**
QQ：2792006529
E-mail：jeep.jipu@gmail.com

**Comment by newpanjing** [comment]
最新的simpleui 以及升级到5.8.1 free版
