### ISSUE TITLE
python版本支持文档更新

### ISSUE THREAD

**Issue by diklios5768** [newpanjing/simpleui#403]
**你希望哪些方面得到优化？**
文档中支持的python版本许久没有更新，最近我试用了python3.9.6版本，依旧是支持的，文档可以更新一下

**留下你的联系方式，以便与你取得联系**
** what would you like to see optimized? * *
QQ：1061995104
E-mail：diklios5768@gmail.com

**Comment by newpanjing** [comment]
嗯 文档是很旧了，我这边测试是可以支持到Python3.11的。下次发布版本就更新下。
