### ISSUE TITLE
actions无法和objects解绑

### ISSUE THREAD

**Issue by bode135** [newpanjing/simpleui#404]
## 问题描述

> 例如: 我想做一个抽奖功能, 从用户列表中抽出一个幸运用户, 不需要选中某个/某些用户.  

- 参考链接: [django admin action without selecting objects](https://stackoverflow.com/questions/4500924/django-admin-action-without-selecting-objects)
- 我调试后发现, django原生admin可以用上述stackoverflow的方案实现. 但simpleui无法实现, 应该是前端做了限制. * 

## 环境
1.Operating System：win10

2.Python Version：3.7

3.Django Version：3.2

4.SimpleUI Version：django-simpleui==2021.10.15

**Comment by newpanjing** [comment]
可以暂时先用simplepro替代下，simplepro支持不选中请求。

**Comment by bode135** [comment]
虽然买了simplepro, 但还是选择手动解决了...

```
pip install bddjango

from bddjango.adminclass import IDAdmin
```
