### ISSUE TITLE
Save button on change_list.html page update all table rows not only the editable row 

### ISSUE THREAD

**Issue by AlyRadwan2020** [newpanjing/simpleui#409]
I have reated `list_editable = ("pickup_date", "pickup_available_time")`  in admin.py file but in the page change_list.html when I edit pickup_date for an selected row in the table I noticed that all the table rows are updated not only the selected one

**Comment by newpanjing** [comment]
Post your admin and Model code

**Comment by AlyRadwan2020** [comment]
admin.py file 
`    list_editable = ("pickup_date", "pickup_available_time")`
When I edit the pickup date for any table row and click the save button , it update all the table rows
![Capture](https://user-images.githubusercontent.com/34564450/154252312-cbda4611-5cda-43dd-b131-60a0a39116cf.PNG)
