### ISSUE TITLE
model中有多个图片字段（StdImageField）时，第二个图片在界面编辑时，“目前”项只显示链接地址，不能预览图片

### ISSUE THREAD

**Issue by carter8225** [newpanjing/simpleui#414]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:

model中有多个图片字段（StdImageField）时，第二个图片在界面编辑时，“目前”项只显示链接地址，不能预览图片

图片字段选用第三方插件 from stdimage.models import StdImageField

**重现步骤**
** repeat step **
1. model.py中定义三个图片字段

logo = StdImageField(max_length=200,
                          upload_to=UploadToUUID(path=timezone.now().strftime('upload/%Y/%m/%d')),
                          verbose_name=u"logo",
                          delete_orphans=True,
                          null=True, blank=True)
    logo_white = StdImageField(max_length=200,
                         upload_to=UploadToUUID(path=timezone.now().strftime('upload/%Y/%m/%d')),
                         verbose_name=u"全白logo",
                         delete_orphans=True,
                         null=True, blank=True)
    default_cover = StdImageField(max_length=200,
                               upload_to=UploadToUUID(path=timezone.now().strftime('upload/%Y/%m/%d')),
                               verbose_name=u"默认封面",
                               delete_orphans=True,
                               null=True, blank=True)

2. 正常配置admin.py
3. 界面显示model数据信息页时， 第二个图片字段的“目前”只显示链接地址，不能预览图片

**环境**
** environment**

1.Operating System：
windows和centos都存在此问题

2.Python Version：
3.9.7

3.Django Version：
3.2.9

4.SimpleUI Version：
2021.11.*
2021.12.7
2022.1

以上版本均有该bug

**Description**

**Comment by newpanjing** [comment]
建议咨询第三方插件
