### ISSUE TITLE
自定义站点注册的模型管理类使用layer对话框按钮报错404

### ISSUE THREAD

**Issue by Ronghefeng** [newpanjing/simpleui#416]
**bug描述**
* 在已有默认 Django admin site 的基础上，继承 Django 的 AdminSite 自定义站点 MyAdminSite，模型管理类 DashboardAdmin（继承 simpleui.admin.AjaxAdmin） 注册到 MyAdminSite，在 DashboardAdmin 添加自定义方法 batch_update_factor，方法使用了layer对话框按钮功能，但是请求的地址是错误的，导致报 404，无法进入到自定义的方法中。
* 理论上应该请求的地址：POST /dashboard-admin/dashboard/monthactiveusers/ajax
* 实际上请求的地址：POST /dashboard-admin/dashboard/monthactiveusers/None
* **但是注册到 Django 默认 admin site 站点，一切正常**

**重现步骤**
1.新增自定义站点
```
class MyAdminSite(AdminSite):

    site_header = "新管理后台"

new_admin_site = MyAdminSite(name="dashboard_admin")
```
2.增加 url 管理
```
urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("dashboard-admin/", new_admin_site.urls, name="dashboard_admin"),
]
```
3.注册模型
```
from simpleui.admin import AjaxAdmin
from django.http.response import JsonResponse
from . import models

class DashboardAdmin(AjaxAdmin):

    actions = ["batch_update_factor"]

    def batch_update_factor(self, request, queryset):

        date = request.POST.get("date", None)
        return JsonResponse(data={"status": "success", "msg": "修改系数成功！"})

    batch_update_factor.short_description = "批量修改系数"
    batch_update_factor.icon = "el-icon-s-promotion"
    batch_update_factor.layer = {
        "title": "弹出层输入框",
        "confirm_button": "确认修改",
        "cancel_button": "取消",
        "width": "50%",
        "labelWidth": "80px",
        "params": [
            {
                "type": "date",
                "key": "date",
                "label": "日期",
                "require": True,
            },
        ],
    }

new_admin_site.register(models.MyModel, DashboardAdmin)

```
4.Django 新站点管理后台页面点击方法，报错 404
![image](https://user-images.githubusercontent.com/42339196/148046204-486ababd-a272-48e2-932e-9b74ec7161b1.png)

**环境**
** environment**

1.Operating System：
MacOS

2.Python Version：
3.9

3.Django Version：
Django==3.1.12

4.SimpleUI Version：
django-simpleui==2022.1

**Comment by newpanjing** [comment]
经测试，不会存在这个问题，请检查自己的url配置。
