### ISSUE TITLE
浏览框较窄时，左侧菜单隐藏后，不再支持三级菜单

### ISSUE THREAD

**Issue by Star-fly-Cheng** [newpanjing/simpleui#418]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:
浏览框较窄时，左侧菜单隐藏后，不再支持三级菜单

**重现步骤**
** repeat step **
1.缩小浏览器直到左侧边框隐藏
2.此时打开菜单只能显示两级菜单

**环境**
** environment**

1.Operating System：Linux
(Windows/Linux/MacOS)....

2.Python Version：3.9

3.Django Version：3.2

4.SimpleUI Version：2021.8.17

**Comment by newpanjing** [comment]
贴的截图。

**Comment by Star-fly-Cheng** [comment]
![image](https://user-images.githubusercontent.com/33115681/173261937-77abe70c-8680-4e04-9f70-2345a888c6e9.png)
![image](https://user-images.githubusercontent.com/33115681/173262007-5efaeab9-bd7c-46bd-a473-6818262f37c8.png)
正常情况下可以显示三级菜单，但是当把窗口缩小直到左侧菜单栏隐藏。
这时候使用菜单就只有二级。
