### ISSUE TITLE
左侧栏收起后无全屏缩小

### ISSUE THREAD

**Issue by Qianzujin** [newpanjing/simpleui#43]
**bug描述**
简单的描述下遇到的bug：

**重现步骤**
1.
2.
3.

**环境**

1.操作系统：
2.python版本：
3.django版本：
4.simpleui版本：

**其他描述**

**Comment by newpanjing** [comment]
已经修复该bug，请升级到2.1。
```shell
pip install django-simpleui --upgrade
```
