### ISSUE TITLE
DateTimeField 不能输入秒钟吗？

### ISSUE THREAD

**Issue by rendaoer** [newpanjing/simpleui#431]
<img width="241" alt="image" src="https://user-images.githubusercontent.com/46780118/162139613-018694e9-a4bc-49b1-ac84-00a2057f8628.png">
不能输入秒钟精度不够，有什么办法可以解决吗

**Comment by newpanjing** [comment]
可以使用[simplepro](https://simpleui.72wo.com/simplepro) 支持精确到秒。

https://simpleui.72wo.com/docs/simplepro/components.html#datetime-%E6%97%A5%E6%9C%9F%E6%97%B6%E9%97%B4%E9%80%89%E6%8B%A9%E5%99%A8

![image](https://user-images.githubusercontent.com/13655483/173168336-24ce9435-0c24-46ee-b75d-5bb1c51447be.png)

**Comment by guanjiawen008** [comment]
链接无法跳转，另外的话，有没有不升级的情况下可以限制秒的精度？
