### ISSUE TITLE
FieldListFilter无法解析

### ISSUE THREAD

**Issue by xianxuhua** [newpanjing/simpleui#438]
**bug描述**
![Xnip2022-06-11_09-34-29](https://user-images.githubusercontent.com/41063489/173167731-63b915e6-f1c0-4da8-a7b9-4c37eb0ac248.jpg)
```
class BaseRangeFilter(admin.filters.FieldListFilter):
    ...
class PeriodMonthRangeFilter(BaseRangeFilter):
    ...
class DeviceAdmin(admin.ModelAdmin):
    list_display = ["name", "category", "depart", "product_date", "period_month", "maintain_status", "actions_html"]
    list_filter = ["category", DepartFilter, "product_date", ["period_month", PeriodMonthRangeFilter]]
```

**简单的描述下遇到的bug：**
自定义了一个范围过滤器，加上之后导致所有过滤器无法显示

**重现步骤**
** repeat step **
1.
2.
3.

**环境**
** environment**

1.Operating System：
MacOS

2.Python Version：
3.9

3.Django Version：
3.2

4.SimpleUI Version：
2022.4.9

**Description**

**Comment by newpanjing** [comment]
参照这个：

https://github.com/newpanjing/simpleui_demo/blob/master/demo/admin.py#L49
