### ISSUE TITLE
最新的字体调节有点差强人意

### ISSUE THREAD

**Issue by ShiningSYK** [newpanjing/simpleui#44]
**bug描述**
简单的描述下遇到的bug：
字体调节放大时，只能放大list_display_links包含的数据

**重现步骤**
1.
2.
3.

**环境**

1.操作系统：win10
2.python版本：3.7
3.django版本：2.2
4.simpleui版本：2.1

**其他描述**
效果如下图所示
![image](https://user-images.githubusercontent.com/45619625/58064716-d5562380-7bb5-11e9-9a42-9ebecd7b93f5.png)

**Comment by newpanjing** [comment]
已经修复此bug，请升级到2.1.1
