### ISSUE TITLE
建议增加一个内置的富文本编辑器

### ISSUE THREAD

**Issue by jeyrce** [newpanjing/simpleui#440]
**你希望增加什么功能？**
** what features do you wish to add? * *
1. 增加一个内置的富文本编辑器
2. 其他提供的富文本编辑器继承后，js和css样式有一些冲突，导致还要稍微修改
3.

**你希望哪些方面得到优化？**
1.
2. 直接集成一个内置的富文本编辑器吧
3.

**留下你的联系方式，以便与你取得联系**
** what would you like to see optimized? * *
QQ：xxxxx
E-mail：jeyrce@gamil.com

**Comment by newpanjing** [comment]
simplepro中提供了

https://simpleui.72wo.com/docs/simplepro/editor.html
