### ISSUE TITLE
建议登录页增加一个简单验证码

### ISSUE THREAD

**Issue by jeyrce** [newpanjing/simpleui#442]
**你希望增加什么功能？**
** what features do you wish to add? * *
1. 登录页增加一个简单验证码，例如字符图片（虽然对于一些开发者来说没用，但是就像user-agent一样总能拦住一批初级）
2.
3.

**你希望哪些方面得到优化？**
1.
2.
3.

**留下你的联系方式，以便与你取得联系**
** what would you like to see optimized? * *
QQ：xxxxx
E-mail：jeyrce@gmail.com

**Comment by newpanjing** [comment]
这个我们计划以插件形式提供，在未来版本的计划之中。

**Comment by newpanjing** [comment]
simplepro 中已经增加
