### ISSUE TITLE
关于自定义logo的问题

### ISSUE THREAD

**Issue by ShiningSYK** [newpanjing/simpleui#45]
**bug描述**
简单的描述下遇到的bug：
在登陆界面的显示中，很完美，但是登陆后，左上角的缩略图显示，出现问题

**重现步骤**
1.
2.
3.

**环境**

1.操作系统：win10+Chrome
2.python版本：3.7
3.django版本：2.2
4.simpleui版本：2.1

**其他描述**
登陆界面展示如下：
![image](https://user-images.githubusercontent.com/45619625/58065896-d1c49b80-7bb9-11e9-85b1-ab9af3c91b17.png)

登陆后的左上角缩略图展示如图
![image](https://user-images.githubusercontent.com/45619625/58065910-dee18a80-7bb9-11e9-9b65-b6ded0f5a8ee.png)

**Comment by newpanjing** [comment]
在即将发布的2.1.1中增加了logo block，可以自定义实现任何大小的logo。
在templates中建立admin文件夹，添加index.html文件并加入以下内容：

```html
    {% extends 'admin/index.html' %}
    {% load static %}
    

   {%block logo}
<!--此处可以包含任意html元素-->
<div>
  <img src="/static/xxx.log">
   <div>XXX管理系统</div>
</div>
    {% endblock %}
```

**Comment by newpanjing** [comment]
已经修复此bug，请升级到2.1.1
