### ISSUE TITLE
How do i remove unnecessary Buttons from the admin panel? 

### ISSUE THREAD

**Issue by MitsukoK** [newpanjing/simpleui#458]
Description:

I have encountered an issue removing the unnecessary buttons displayed on the top panel of my project. I would like to request assistance in removing these buttons from the panel. A screenshot of the issue has been attached for your reference.

![2023-03-12_06-50](https://user-images.githubusercontent.com/114921277/224518551-048e6e48-c755-4db9-b4fa-1dcd5e6c1f07.png)

Additionally, I have also noticed two other issues in my project, which are identified as #445 and #447. I would appreciate it if these issues could also be addressed in a timely manner.

**环境**
** environment**

1. Operating System： Linux

2. Python Version：3.10.9

3. Django Version：4.1.2

4. SimpleUI Version：2023.3.1

**Comment by nightzjp** [comment]
![image](https://user-images.githubusercontent.com/73635091/230298839-f80889e0-05a9-4572-847b-973bf0c8a909.png)
![image](https://user-images.githubusercontent.com/73635091/230299197-66d8094f-07d7-4939-852d-8d464b043cff.png)
