### ISSUE TITLE
Static file丢失

### ISSUE THREAD

**Issue by penghuixie** [newpanjing/simpleui#461]
Django==3.2.6
django-simpleui==2023.3.1

不管是在debug = True 还是 False的情况下都会出现一个文件404错误
"GET /static/admin/simpleui-x/elementui/umd/locale/en.js?_=2.1.2 HTTP/1.1" 404

且使用uwsgi部署后，会出现部分图标缺失的情况
图标缺失时:
![image](https://user-images.githubusercontent.com/117330307/230847339-dceb9994-72d4-4763-b611-97adbcd46336.png)
![image](https://user-images.githubusercontent.com/117330307/230847534-d4d01659-af49-4a91-9338-b8f7014b9b82.png)

图标正常时(debug = True): 
![image](https://user-images.githubusercontent.com/117330307/230847624-90306595-21ab-4606-9c95-2ce0761f57c2.png)
![image](https://user-images.githubusercontent.com/117330307/230847691-2d09e9c1-c67f-4d1d-b902-22e76be2f110.png)

有任何疑问或解决方法，请联系: a_ziki@163.com
谢谢

**Comment by nightzjp** [comment]
静态文件用nginx代理了吗？
