### ISSUE TITLE
layer对话框 date 的默认值没有动态更新

### ISSUE THREAD

**Issue by Bisns** [newpanjing/simpleui#466]
**bug描述**
* *Bug description * * 

简单的描述下遇到的bug：
Briefly describe the bugs encountered:

请问 layer对话框 date 的默认值value设置成 arrow.now()，没有更新吗？
第二天还是显示第一天的日期，然后重启uwsgi，默认值会变成当天的

**重现步骤**
** repeat step **
layer date组件 'value': arrow.now().format('ddd MMM DD YYYY')

**环境**
** environment**

1.Operating System：
(Windows/Linux/MacOS)....
Ubuntu 22.04

2.Python Version：Python 3.10

3.Django Version：4.2.3

4.SimpleUI Version：2023.3.1

5. arrow Version:1.2.3

**Description**

**Comment by uncle-lv** [comment]
因为Admin类只会在应用启动时加载，所以实际上`arrow.now().format('ddd MMM DD YYYY')`只在你启动服务时，被执行了。不重启应用的话，值会一直都是启动时的时间
