### ISSUE TITLE
关于后台menu打开了一堆窗口,懒得右键关闭,想在一地方有个一键关闭所有

### ISSUE THREAD

**Issue by zyxy3344** [newpanjing/simpleui#47]
**你希望增加什么功能？**
1.关于后台menu打开了一堆窗口,懒得右键关闭,想在一地方加个一键关闭所有

**留下你的联系方式，以便与你取得联系**
QQ：705301804

**Comment by newpanjing** [comment]
element-ui有局限性，暂时不好实现。坐等大神们来实现。
