### ISSUE TITLE
Enable private vulnerability reporting

### ISSUE THREAD

**Issue by manuel-sommer** [newpanjing/simpleui#471]
Hi,

Could you please also enable "private vulnerability reporting" in here:
https://github.com/newpanjing/simpleui/security
![grafik](https://github.com/newpanjing/simpleui/assets/47991713/57d0557d-bcbe-45b2-9045-b3d29162ec87)

Then, please check if the following link in your Security.md is working:
_"Please report security issues to https://github.com/newpanjing/simpleui/security/advisories/new."_

**Comment by manuel-sommer** [comment]
@newpanjing reminder

**Comment by manuel-sommer** [comment]
reminder @newpanjing

**Comment by manuel-sommer** [comment]
reminder @newpanjing

**Comment by Haoke98** [comment]
> Hi,
> 
> Could you please also enable "private vulnerability reporting" in here: https://github.com/newpanjing/simpleui/security ![grafik](https://private-user-images.githubusercontent.com/47991713/263618506-57d0557d-bcbe-45b2-9045-b3d29162ec87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTYyNDQsIm5iZiI6MTcxMDQ5NTk0NCwicGF0aCI6Ii80Nzk5MTcxMy8yNjM2MTg1MDYtNTdkMDU1N2QtYmNiZS00NWIyLTkwNDUtYjNkMjkxNjJlYzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDA5NDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ODg0NzU4ZTNlZTcxN2RmNTQ5Yjc1YzZlZmJlNzczMWUzNDM2ZWYyNWE3MzVjZWRjZjk4YjFhZDE5YzAxMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C0cUm34wQ2yKRot4KPq7CV9uEe5JzSbOwqr6Av8hIp4)
> 
> Then, please check if the following link in your Security.md is working: _"Please report security issues to https://github.com/newpanjing/simpleui/security/advisories/new."_

same request

**Comment by manuel-sommer** [comment]
@Haoke98 and @newpanjing , yes this is the same request, but the security policy is not yet activated and I try to submit multiple XSS issues in a safe way, but this is currently not possible.
