### ISSUE TITLE
djagno 5 版本后logout 退出方式修改为了post请求，需要自己覆盖下，给大家提醒下

### ISSUE THREAD

**Issue by pangxiaobin** [newpanjing/simpleui#487]
参考链接 https://docs.djangoproject.com/en/5.0/releases/4.1/

**Comment by phper01** [comment]
请问怎么覆盖用哪个覆盖

**Comment by pangxiaobin** [comment]
> 请问怎么覆盖用哪个覆盖

url 匹配是从上往下，自己实现一个logout的退出的view，把logout请求的path写在admin之前，然后绑定自己的视图

**Comment by ljzecg** [comment]
项目的urls.py中
```
from django.urls import path
from django.contrib.auth import logout
from django.shortcuts import redirect


def bug_fix_logout_view(request):
    logout(request)
    return redirect("/admin/")
```

然后urlpatterns中，在admin前面加上：
```
urlpatterns = [
...
path('admin/logout/', bug_fix_logout_view, name="logout"),
path('admin/', admin.site.urls),
...
]
```

不知道这样写对不对，反正django 5测试下来没问题，能够正常退出登录，重定向到登录界面

**Comment by newpanjing** [comment]
该bug已经在2024.03.25中修复。

**Comment by wineejam** [comment]
django-simpleui       2024.8.28 版本中存在同样问题，使用path('admin/logout/', bug_fix_logout_view, name="logout")方式解决了
