### ISSUE TITLE
希望能够提供重写simpleui相较于原版后台添加的保存键的文档

### ISSUE THREAD

**Issue by davincilll** [newpanjing/simpleui#497]
我的需求是希望将这个保存键修改为一键发货
另外因为我的后台模型显示比较复杂，使用这个默认的保存开销会比较大，会产生很多相同的sql查询，我希望能够进行优化

**Comment by newpanjing** [comment]
建议查阅django文档，simpleui只是一个ui皮肤，不参与后台代码和业务逻辑交互。
