### ISSUE TITLE
Good thing! Wishing new update!

### ISSUE THREAD

**Issue by duxiaoyang06** [newpanjing/simpleui#5]
Bugs:
1.Cannot refresh the label opened.
Suggestions:
1.It's better if 'layui-header my-header' can be defined by self.
2.It's better if the style and color can be customed same as django admin style.

**Comment by newpanjing** [comment]
感谢反馈。将于近期发布1.4.7 修复。

**Comment by duxiaoyang06** [comment]
其他新发现的bug:
1.列表页的过滤条件下拉框，如果字符串太长，内容不能被正确显示
2.按条件选了数据之后，再选“全部xxx”，将不会有数据被选出来

**Comment by newpanjing** [comment]
好的，收到。

**Comment by duxiaoyang06** [comment]
新bug：
同样是列表页的过滤条件下拉框，如果字段是数字类型，筛选条件不显示

**Comment by duxiaoyang06** [comment]
新bug：
同样是列表页的过滤条件下拉框，如果字段是数字类型，筛选条件不显示，改成字符串类型后，条件显示不全，尝试了两个列，两列的条件值为1-18或者0-6

**Comment by duxiaoyang06** [comment]
新bug：
同样是列表页的过滤条件下拉框，如果字段是数字类型，筛选条件不显示，改成字符串类型后，条件显示不全，尝试了两个列，两列的条件值为1到18或者0到6

尝试了几次，发现这个bug具体是只显示值的第二个字符，1到18，只显示0到8，其实是10到18，字符“1”没有显示，0到6没有显示是因为他们没有第二个字符。

'level 0' 'level 1' 'level 2' 显示了三行字符’e‘，也都是第二个字符。

但是有的字段值全是英文大写，这样的没有问题。

**Comment by duxiaoyang06** [comment]
新bug：
同样是列表页的过滤条件下拉框，如果字段是数字类型，筛选条件不显示，改成字符串类型后，条件显示不全，尝试了两个列，两列的条件值为1到18或者0到6

尝试了几次，发现这个bug具体是只显示值的第二个字符，1到18，只显示0到8，其实是10到18，字符“1”没有显示，0到6没有显示是因为他们没有第二个字符。

'level 0' 'level 1' 'level 2' 显示了三行字符’e‘，也都是第二个字符。

但是有的字段值全是带choices选项的，这样的没有问题。

**Comment by newpanjing** [comment]
bug已经修复，并且发布了1.4.7版本
升级：pip install django-simpleui --upgrade
详细列表：https://github.com/newpanjing/simpleui#version-147
