### ISSUE TITLE
django2.2.3使用中出现的问题

### ISSUE THREAD

**Issue by yanlianhanlin** [newpanjing/simpleui#52]
**bug描述**
简单的描述下遇到的bug：
1.增加加，删除页面谷歌浏览器不适配
2.增加内容之后得点击返回多次才能回到对应的列表页
3.再list_filter中使用SimpleListFilter时报
Exception:  object has no attribute 'field'
Exception Location: \venv\lib\site-packages\simpleui\templatetags\simpletags.py in load_dates, line 40

**环境**

1.操作系统：
2.python版本：3.7.3
3.django版本：2.2.3
4.simpleui版本：2.1

**其他描述**

**Comment by newpanjing** [comment]
model或者admin相关代码能贴出来一下吗？

**Comment by WalkerWang731** [comment]
#48 是否和这个是同一个问题？

**Comment by yanlianhanlin** [comment]
是的

**Comment by yanlianhanlin** [comment]
@WalkerWang731 和你说的那个情况是一样的

**Comment by newpanjing** [comment]
已经修复此bug，请升级到2.1.1
