### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by yanlianhanlin** [newpanjing/simpleui#53]
**你希望增加什么功能？**
1.能否添加自定义快速操作，根据自己的需要显示快速操作
2.能否添加自定义设置最近操作，设置显示条数、内容等，添加一个最近操作列表查看
3.能否添加自定义服务器信息显示，现在服务器信息模块只能整体显示或是隐藏

**Comment by newpanjing** [comment]
这个是需要改动部分服务器代码实现，simpleui只是个ui框架。后续可以考虑加上。
