### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by ClassmateLin** [newpanjing/simpleui#55]
**你希望增加什么功能？**
1. 添加内联模型的界面。

**Comment by newpanjing** [comment]
举个栗子？

**Comment by ClassmateLin** [comment]
class AInline(admin.TabularInline):
    model =A

@admin.register(B)
class Bdmin(admin.ModelAdmin):
    inlines = [AInline,]

**Comment by newpanjing** [comment]
@ClassmateLin 详细请看#31 不过目前有点小bug。
