### ISSUE TITLE
最近动作修改显示verbose_name设置的内容

### ISSUE THREAD

**Issue by yanlianhanlin** [newpanjing/simpleui#58]
最近动作修改显示verbose_name设置的内容而不是键值
![112](https://user-images.githubusercontent.com/9565630/58307688-165a6c00-7e32-11e9-837f-98912880f43b.png)

**Comment by newpanjing** [comment]
该显示内容simpleui无法更改，如果需要改请自己实现自定义的日志，在操作模块的时候将log写入数据库。
