### ISSUE TITLE
与django-import-export集成的时候遇到的兼容性问题

### ISSUE THREAD

**Issue by pandadriver** [newpanjing/simpleui#63]
**bug描述**
简单的描述下遇到的bug：
按照simpleui_demo的用了django_import_export，然后导入导出的图标跟过滤搜索的这些重叠了
![TIM图片20190524152217](https://user-images.githubusercontent.com/31982633/58310109-6805f500-7e38-11e9-8f6c-36c5462af0f6.png)

建议是否可以增加配置把过滤搜索这些框下降一行吗？

**重现步骤**
1.
2.
3.

**环境**
Django==2.2.1
django-import-export==1.2.0
django-simpleui==2.1

**其他描述**

**Comment by newpanjing** [comment]
下个版本进行优化

**Comment by newpanjing** [comment]
下个版本改成这种：
![image](https://user-images.githubusercontent.com/13655483/58747774-5066e600-84a2-11e9-86d6-0ed15cb954f1.png)

**Comment by newpanjing** [comment]
已经修复了此问题，请更新至2.1.2
```shell
pip install django-simpleui -U
```

**Comment by izqutcom** [comment]
> 下个版本改成这种：
> ![image](https://user-images.githubusercontent.com/13655483/58747774-5066e600-84a2-11e9-86d6-0ed15cb954f1.png)

使用django-import-export后，使用自定义按钮，可以导入，无法导出。去掉自定义按钮的话正常。
