### ISSUE TITLE
跨关联关系查询不显示verbose_name值

### ISSUE THREAD

**Issue by yanlianhanlin** [newpanjing/simpleui#64]
![122](https://user-images.githubusercontent.com/9565630/58313113-67bd2800-7e3f-11e9-8456-575f266de6bc.png)
list_filer 设置ManyToManyField字段查询框不显示verbose_name设置的值

**Comment by newpanjing** [comment]
将在下个版本对此问题进行优化

**Comment by yanlianhanlin** [comment]
好的

**Comment by newpanjing** [comment]
已经修复了此问题，请更新至2.1.2
```shell
pip install django-simpleui -U
```
