### ISSUE TITLE
删除返回无效

### ISSUE THREAD

**Issue by yanlianhanlin** [newpanjing/simpleui#66]
点击删除按钮进入删除确认页点击返回无法返回之前的页面
![114](https://user-images.githubusercontent.com/9565630/58362020-5cacdb00-7ec5-11e9-9b73-5003abc4102e.png)

**Comment by newpanjing** [comment]
@yanlianhanlin simpleui版本多少？

**Comment by yanlianhanlin** [comment]
最新版本2.1.1

**Comment by newpanjing** [comment]
已经修复了此问题，请更新至2.1.2
```shell
pip install django-simpleui -U
```
