### ISSUE TITLE
admin中自定义action icon设置问题

### ISSUE THREAD

**Issue by s263628839** [newpanjing/simpleui#68]
**你希望增加什么功能？**
1.app的admin中自定义的action的button图标只能是默认的白色的，只能设置.short_description属性，不能设置.icon属性。
2.自定义的action多了之后button排列起来不好看，希望能够解决这个问题

**你希望哪些方面得到优化？**
1.希望能够增加icon属性设置，这样自定义的action对应的button就可以跟优化后的simpleui一致。
2.自定义的action多了之后button排列起来不好看，希望能够解决这个问题

**Comment by newpanjing** [comment]
下个版本解决此问题。

**Comment by newpanjing** [comment]
@s263628839 
已经修复了此问题，请更新至2.1.2
```shell
pip install django-simpleui -U
```
