### ISSUE TITLE
search_field

### ISSUE THREAD

**Issue by LehongWei** [newpanjing/simpleui#7]
所有的搜索，在第一页显示正常，但是在第二页的时候就丢失了搜索关键字，也就是说这个第二页就是当前页面所有数据分页之后的第二页

**Comment by newpanjing** [comment]
感谢反馈。将于近期发布1.4.7 修复。

**Comment by newpanjing** [comment]
bug已经修复，并且发布了1.4.7版本
升级：pip install django-simpleui --upgrade
详细列表：https://github.com/newpanjing/simpleui#version-147
