### ISSUE TITLE
希望优化部分组件的显示效果

### ISSUE THREAD

**Issue by zacharyliang** [newpanjing/simpleui#72]
**你希望哪些方面得到优化？**
1. 列表的行高可以加大一点，现在感觉太密了
2. checkbox样式可以优化一下，默认的太丑了
3. BooleanField字段的显示效果可以改成switch开关的效果，这样会更好看
4. BooleanField的筛选下拉里面显示可以改成是、否吗，或者可以自定义，现在显示的Ture、False不怎么友好啊

**留下你的联系方式，以便与你取得联系**
QQ：326672861
邮箱：mail@lianghongbo.com

**Comment by newpanjing** [comment]
我也希望替换内置的所有组件，但是django的机制不允许。因为每一个字段或者理解为控件，都是一个widgets，如果要重写这些组件的话，需要改动所有的代码。把model定义时的字段替换为自己的。所以暂时不考虑优化这块。如果后续有好的方式可以实现的话，可以考虑优化改进。
