### ISSUE TITLE
登陆页样式加载不全无法输入用户名密码

### ISSUE THREAD

**Issue by pokededan** [newpanjing/simpleui#76]
**bug描述**
简单的描述下遇到的bug：
打开admin登陆页加载很慢，并且样式不全，只有logo和登陆，用户名密码输入框没有了。希望大佬看到了能回复我

**重现步骤**
debug = True  
![image](https://user-images.githubusercontent.com/49021805/58944703-f7a29080-87b4-11e9-8489-f5e554f12057.png)

**环境**

1.操作系统：win7，win10
2.python版本：3.6
3.django版本：2.1
4.simpleui版本：2.1

**其他描述**

**Comment by pokededan** [comment]
糟了，我是不是不应该单独新建issue哦

**Comment by newpanjing** [comment]
经过测试，是element-ui和vue的js文件加载过慢，建议交由nginx处理，下个版本将对所有js文件进行合并，以减少网络请求次数。

**Comment by newpanjing** [comment]
在2.1.3中已经修复该问题
```
pip install django-simpleui -U
```
@pokededan
