### ISSUE TITLE
加载太慢

### ISSUE THREAD

**Issue by Winspain** [newpanjing/simpleui#77]
**bug描述**
简单的描述下遇到的bug：
等待了大概1min，登录界面才出来

**重现步骤**
1.
2.
3.

**环境**

1.操作系统：
2.python版本：3.6
3.django版本：2.1.5
4.simpleui版本：2.1.1

**其他描述**

**Comment by newpanjing** [comment]
经过测试，是element-ui和vue的js文件加载过慢，建议交由nginx处理，下个版本将对所有js文件进行合并，以减少网络请求次数。

**Comment by newpanjing** [comment]
在2.1.3中已经修复该问题
```
pip install django-simpleui -U
```
@Winspain

**Comment by hiwoshixiaoyu** [comment]
这个问题得修改一下，经常莫名卡主的
