### ISSUE TITLE
Windows系统显示问题，期待更新

### ISSUE THREAD

**Issue by duxiaoyang06** [newpanjing/simpleui#8]
1.windows开始任务栏调到左侧或者右侧的时候，13寸本1920*1680分辨率，列表页显示左右侧显示空白，横纵滚动条无法拖动。
2.打开页面前，先打开浏览器右键“检查”选项，再打开页面，关掉“检查”，页面无法把“检查”的位置补充上显示网站内容

**Comment by newpanjing** [comment]
能不能截个图看看

**Comment by duxiaoyang06** [comment]
要不我加你微信吧 哈哈 我微信duxiaoyang2011
![image](https://user-images.githubusercontent.com/2735347/53621522-bccb1280-3c31-11e9-8f4c-209edb5e4453.png)
![image](https://user-images.githubusercontent.com/2735347/53621555-dd936800-3c31-11e9-892d-9b299a40074a.png)

**Comment by qylove516** [comment]
我自定义一个过滤器，放在  list_filter 的列表中，要原生的  admin 下是可以出现过滤的效果，但在 simpleui中过滤数据不生效，我的代码如下：
`
# model.py
class Price(models.Model):
    name = models.CharField('名称', max_length=64, blank=True, null=True)
    num = models.IntegerField('价格', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '价格'
        verbose_name_plural = '价格'

# admin.py
from django.contrib import admin
from goods import models

class PriceFilter(admin.SimpleListFilter):
    """
    自定义价格过滤器
    """
    title = '价格'
    parameter_name = 'num'

    def lookups(self, request, model_admin):
        return (
            ('0', '高价'),
            ('1', '中价'),
            ('3', '低价'),
        )

    def queryset(self, request, queryset):
        if self.value() == '0':
            return queryset.filter(num__gt='555')
        if self.value() == '1':
            return queryset.filter(num__gte='222', num__lte='555')
        if self.value() == '3':
            return queryset.filter(num__lt='222')


class PriceAdmin(admin.ModelAdmin):
    list_display = ['name', 'num']
    ordering = ['-num']
    list_filter = [PriceFilter,]
`
请查看，如果有什么不太清楚我，可以随时@我，谢谢！
