### ISSUE TITLE
后台首页展开合并按钮滑动卡顿

### ISSUE THREAD

**Issue by wefbnkop** [newpanjing/simpleui#80]
在点击合并菜单按钮时候，图标旁边会显示半个字符。另合并左侧菜单后，鼠标移动到左上角首页按钮，默认右侧显示首页字样，挡住了展开/合并按钮，影响连续操作。希望改进

**Comment by newpanjing** [comment]
2.1.4中已经修复，请升级
```
pip install django-simpleui -U
```
