### ISSUE TITLE
django 2.1.7  django-celery 3.3.0 用simpleui时页面报错

### ISSUE THREAD

**Issue by githublitao** [newpanjing/simpleui#81]
**bug描述**
简单的描述下遇到的bug：
django 2.1.7  django-celery 3.3.0 用simpleui时
![image](https://user-images.githubusercontent.com/27721835/59496730-a8e7ab80-8ec4-11e9-98c5-736cab048bc3.png)

**重现步骤**
1. 
2.
3.

**环境**

1.操作系统：mac
2.python版本：3.6
3.django版本：2.1.7
4.simpleui版本：2.1.2.603  
5.django-celery： 3.30

**其他描述**

**Comment by newpanjing** [comment]
2.1.4中已经修复，请升级
```
pip install django-simpleui -U
```

**Comment by benma9** [comment]
@newpanjing  给力1·

**Comment by benma9** [comment]
@newpanjing  集成 Django-guardian 也有bug，点击链接无效
