### ISSUE TITLE
定义的全局Action无法显示

### ISSUE THREAD

**Issue by JohnYan2017** [newpanjing/simpleui#83]
**bug描述**
Action为全局函数时, Admin 不显示Action 按钮

**重现步骤**
1. 将Action 函数定义为全局
2. admin中引用action, 如actions = [make_public,]
3. 页面不会显示任务action 按钮

**环境**

1.操作系统：
2.python版本：3.6
3.django版本：2.1
4.simpleui版本：2.1.3

**其他描述**

**Comment by newpanjing** [comment]
具体的代码能贴出来下么？

**Comment by JohnYan2017** [comment]
def make_public(modeladmin, request, queryset):
    queryset.update(is_public=True)
make_public.short_description = "公开"

@admin.register(models.DBSetup)
class DBSetupAdmin(admin.ModelAdmin):
    actions = [make_public,]

**Comment by newpanjing** [comment]
可以先暂时用字符串将方法名包裹起来，下个版本解决这个问题

```
actions = ['make_public',]
```

**Comment by newpanjing** [comment]
2.1.4中已经修复，请升级
```
pip install django-simpleui -U
```
