### ISSUE TITLE
admin排序

### ISSUE THREAD

**Issue by mn6538** [newpanjing/simpleui#84]
**你希望哪些方面得到优化？**
管理员后台排序只能排一个字段，多于一个，到了第二页就开始乱序了

**留下你的联系方式，以便与你取得联系**
QQ：550572368
邮箱：550572368@qq.com

**Comment by newpanjing** [comment]
了解。

**Comment by newpanjing** [comment]
2.1.4中已经修复，请升级
```
pip install django-simpleui -U
```
