### ISSUE TITLE
index.css和index.js下载失败

### ISSUE THREAD

**Issue by githublitao** [newpanjing/simpleui#90]
**bug描述**
简单的描述下遇到的bug：
升级版本后index.css和index.js加载失败

**重现步骤**
1.
![image](https://user-images.githubusercontent.com/27721835/59731521-068b4780-9279-11e9-8905-dc6beb94fb9d.png)

2.
3.

**环境**

1.操作系统：mac
2.python版本：3.6
3.django版本：2.1.7
4.simpleui版本：2.1.4

**其他描述**

**Comment by newpanjing** [comment]
```
python3 manage.py collectstatic
```
这是基础问题
