### ISSUE TITLE
首页设置不生效

### ISSUE THREAD

**Issue by StormSprint** [newpanjing/simpleui#95]
# 简单的描述下遇到的bug：
### Q1:教程中修改默认首页，以下设置不生效
`SIMPLEUI_HOME_PAGE = 'https://www.baidu.com'`
`SIMPLEUI_HOME_TITLE = '百度一下你就知道'`
`SIMPLEUI_HOME_ICON = 'fa fa-user'`

### Q2:修改LOGO不生效
`SIMPLEUI_LOGO = 'fa fa-user'`

### Q3:重写首页不生效
<img width="600" alt="image" src="https://user-images.githubusercontent.com/20579112/59910689-02138a00-9445-11e9-83bc-ea3190e517a0.png">

# **环境**

1.操作系统：10.14.5
2.python版本：3.7
3.django版本：2.2.2
4.simpleui版本：2.1.4.619

**Comment by newpanjing** [comment]
经测试，3个问题都不存在。建议自己下载demo查看。
[http://github.com/newpanjing/simpleui_demo](http://github.com/newpanjing/simpleui_demo)
