### ISSUE TITLE
希望支持用户PC无需访问互联网即可从服务器上获取CSS、JS等文件（element、vue）

### ISSUE THREAD

**Issue by andyho1107** [newpanjing/simpleui#96]
SimpleUI 配合 Django 挺好用的，但是我们需要部署到内部的服务器上，用户的PC是无法访问互联网的，就会出现无法通过互联网获取CSS、JS等文件（element、vue）的情况，希望可以提供方法以支持这种情况。

**留下你的联系方式，以便与你取得联系**
QQ：42125783
邮箱：42125783@qq.com

**Comment by andyho1107** [comment]
`SIMPLEUI_STATIC_OFFLINE = True`

**Comment by lixiaofeng1993** [comment]
> `SIMPLEUI_STATIC_OFFLINE = True`

额，这个在哪里设置呢？
