### ISSUE TITLE
主页右侧显示优化

### ISSUE THREAD

**Issue by cqrichard2018** [newpanjing/simpleui#99]
**你希望增加什么功能？**
1.首页右侧如下显示：
simpleui 主页，报告问题
version 2.1.4.619   gitee/github链接
请问这部分内容能通过setting,屏蔽掉吗，如无法屏蔽，能否将这个区域缩小点，放在页面下方也好，谢谢！

**留下你的联系方式，以便与你取得联系**
邮箱：23420650@qq.com

**Comment by newpanjing** [comment]
文档有隐藏的说明，请自行查阅文档。
